// ─── Game Data ───────────────────────────────────────────────────────────────
// Pares de conceptos opuestos para el dial. Cada uno es [extremoIzquierdo, extremoDerecho].
export const SPECTRUMS: [string, string][] = [
  ["Malo", "Bueno"],
  ["Barato", "Caro"],
  ["Aburrido", "Divertido"],
  ["Feo", "Lindo"],
  ["Inútil", "Útil"],
  ["Común", "Raro"],
  ["Fácil", "Difícil"],
  ["Individual", "Grupal"],
  ["Antiguo", "Moderno"],
  ["Realista", "Fantasioso"],
  ["Seguro", "Peligroso"],
  ["Silencioso", "Ruidoso"],
  ["Simple", "Complejo"],
  ["Local", "Global"],
  ["Serio", "Gracioso"],
  ["Chico", "Grande"],
  ["Rápido", "Lento"],
  ["Frío", "Caliente"],
  ["Triste", "Feliz"],
  ["Saludable", "Poco saludable"],
  ["Formal", "Informal"],
  ["Predecible", "Sorprendente"],
  ["Innecesario", "Imprescindible"],
  ["Discreto", "Llamativo"],
  ["Relajado", "Estresante"],
  ["Injusto", "Justo"],
  ["Sobrevalorado", "Subestimado"],
  ["Práctico", "Inútil en la práctica"],
  ["De niño", "De adulto"],
  ["Barato de mantener", "Caro de mantener"],
  ["Tranquilo", "Caótico"],
  ["Olvidable", "Memorable"],
  ["Bajo presupuesto", "Alto presupuesto"],
  ["Se hace en soledad", "Se hace en grupo"],
  ["De cerca", "De lejos"],
  ["Vergonzoso", "Digno de orgullo"],
  ["Romántico", "Práctico"],
  ["Tacaño", "Generoso"],
  ["Valiente", "Cobarde"],
  ["Organizado", "Desordenado"],
  ["Puntual", "Impuntual"],
  ["Egoísta", "Solidario"],
  ["Introvertido", "Extrovertido"],
  ["Optimista", "Pesimista"],
  ["Testarudo", "Flexible"],
  ["Elegante", "Informal"],
  ["Exagerado", "Moderado"],
  ["Auténtico", "Falso"],
  ["Duradero", "Descartable"],
  ["Delicado", "Resistente"],
  ["Sano", "Adictivo"],
  ["Caro por gusto", "Caro por necesidad"],
  ["De lujo", "Low cost"],
  ["Se olvida rápido", "Se recuerda para siempre"],
  ["Para hacer solo", "Para hacer acompañado"],
  ["Recomendable", "Evitable"],
  ["Para toda la familia", "Solo para adultos"],
  ["Se aprende rápido", "Lleva años dominarlo"],
  ["Sirve en una emergencia", "Es un capricho"],
  ["Tiene mala fama", "Tiene buena fama"],
  ["Da vergüenza admitirlo", "Da orgullo admitirlo"],
  ["Es una pérdida de tiempo", "Vale la pena el tiempo"],
  ["Mejor de noche", "Mejor de día"],
  ["Ideal para el verano", "Ideal para el invierno"],
  ["Típico de Argentina", "Típico de otro país"],
  ["Se hace bien borracho", "Nunca se hace borracho"],
  ["Cosa de nerd", "Cosa de popular"],
  ["Sobrevive sin batería", "Necesita batería"],
  ["Se consigue fácil", "Es difícil de conseguir"],
  ["Ideal para regalar", "Mal regalo"],
  ["Mejora con el tiempo", "Empeora con el tiempo"],
  ["Se explica en 5 segundos", "Necesita una charla larga"],
  ["Apto para toda edad", "Solo para expertos"],
  ["Da hambre", "Da sueño"],
  ["Genera adicción", "Da lo mismo"],
  ["Te hace quedar bien", "Te hace quedar mal"],
];
