// ─── Game Data ───────────────────────────────────────────────────────────────
// Pares de conceptos opuestos para el dial. Cada uno es [extremoIzquierdo, extremoDerecho].
export const SPECTRUMS = [
  ["Malo", "Bueno"],
  ["Barato", "Caro"],
  ["Aburrido", "Divertido"],
  ["Feo", "Lindo"],
  ["Inútil", "Útil"],
  ["Común", "Raro"],
  ["Fácil", "Difícil"],
  ["Individual", "Grupal"],
  ["Antiguo", "Moderno"],
  ["Realista", "Fantasioso"],
  ["Seguro", "Peligroso"],
  ["Silencioso", "Ruidoso"],
  ["Simple", "Complejo"],
  ["Local", "Global"],
  ["Serio", "Gracioso"],
  ["Chico", "Grande"],
  ["Rápido", "Lento"],
  ["Frío", "Caliente"],
  ["Triste", "Feliz"],
  ["Saludable", "Poco saludable"],
  ["Formal", "Informal"],
  ["Predecible", "Sorprendente"],
  ["Innecesario", "Imprescindible"],
  ["Discreto", "Llamativo"],
  ["Relajado", "Estresante"],
  ["Injusto", "Justo"],
  ["Sobrevalorado", "Subestimado"],
  ["Práctico", "Inútil en la práctica"],
  ["De niño", "De adulto"],
  ["Barato de mantener", "Caro de mantener"],
  ["Tranquilo", "Caótico"],
  ["Olvidable", "Memorable"],
  ["Bajo presupuesto", "Alto presupuesto"],
  ["Se hace en soledad", "Se hace en grupo"],
  ["De cerca", "De lejos"],
  ["Vergonzoso", "Digno de orgullo"],
];
