// ─── Game Data ───────────────────────────────────────────────────────────────
export interface Category {
  label: string;
  icon: string;
  words: string[];
}

export const CATEGORIES: Record<string, Category> = {
  futbolistas: {
    label: "Jugadores de Fútbol",
    icon: "⚽",
    words: [
      "Messi",
      "Cristiano Ronaldo",
      "Neymar",
      "Mbappé",
      "Haaland",
      "Benzema",
      "Lewandowski",
      "Salah",
      "De Bruyne",
      "Modric",
      "Vinicius Jr",
      "Pedri",
      "Gavi",
      "Bellingham",
      "Lautaro Martínez",
      "Álvarez",
      "Dybala",
      "Di María",
      "Rooney",
      "Gerrard",
      "Lampard",
      "Beckham",
      "Henry",
      "Zidane",
      "Ronaldinho",
      "Maradona",
      "Pelé",
      "Buffon",
      "Casillas",
      "Neuer",
      "Ter Stegen",
      "De Gea",
      "Oblak",
      "Courtois",
      "Alisson",
      "Ramos",
      "Piqué",
      "Varane",
      "Trent Alexander-Arnold",
      "Marcelo",
      "Griezmann",
      "Suárez",
      "Cavani",
      "Agüero",
      "Higuaín",
      "Tevez",
      "Riquelme",
      "Verón",
      "Kaká",
      "Iniesta",
      "Xavi",
      "Puyol",
      "Van Dijk",
      "Kanté",
      "Pogba",
    ],
  },
  selecciones: {
    label: "Selecciones de Fútbol",
    icon: "🏆",
    words: [
      "Argentina",
      "Brasil",
      "Francia",
      "Alemania",
      "España",
      "Portugal",
      "Italia",
      "Inglaterra",
      "Países Bajos",
      "Bélgica",
      "Uruguay",
      "Colombia",
      "México",
      "Japón",
      "Senegal",
      "Marruecos",
      "Ghana",
      "Ecuador",
      "Perú",
      "Chile",
      "Paraguay",
      "Australia",
      "Croacia",
      "Suiza",
      "Dinamarca",
      "Polonia",
      "Suecia",
      "Serbia",
      "Turquía",
      "Ucrania",
      "Costa Rica",
      "Panamá",
      "Venezuela",
      "Túnez",
      "Argelia",
      "Camerún",
      "Nigeria",
      "Irán",
      "Arabia Saudita",
      "Catar",
      "Corea del Sur",
      "Estados Unidos",
      "Canadá",
      "Gales",
      "Escocia",
    ],
  },
  actores: {
    label: "Actores Famosos",
    icon: "🎬",
    words: [
      "Tom Hanks",
      "Brad Pitt",
      "Leonardo DiCaprio",
      "Angelina Jolie",
      "Meryl Streep",
      "Scarlett Johansson",
      "Robert Downey Jr",
      "Johnny Depp",
      "Will Smith",
      "Denzel Washington",
      "Morgan Freeman",
      "Anthony Hopkins",
      "Cate Blanchett",
      "Natalie Portman",
      "Julia Roberts",
      "Jennifer Aniston",
      "Sandra Bullock",
      "Nicole Kidman",
      "Ryan Reynolds",
      "Ryan Gosling",
      "Chris Evans",
      "Chris Hemsworth",
      "Dwayne Johnson",
      "Keanu Reeves",
      "Joaquin Phoenix",
      "Tom Cruise",
      "Harrison Ford",
      "Al Pacino",
      "Robert De Niro",
      "Jack Nicholson",
      "Penélope Cruz",
      "Antonio Banderas",
      "Salma Hayek",
      "Emma Watson",
      "Emma Stone",
      "Margot Robbie",
      "Zendaya",
      "Timothée Chalamet",
      "Tom Holland",
      "Robert Pattinson",
      "Jason Momoa",
      "Gal Gadot",
      "Charlize Theron",
      "Hugh Jackman",
      "Samuel L. Jackson",
      "Matthew McConaughey",
      "Christian Bale",
    ],
  },
  historicos: {
    label: "Personajes Históricos",
    icon: "📜",
    words: [
      "Napoleón Bonaparte",
      "Julio César",
      "Alejandro Magno",
      "Cleopatra",
      "Leonardo Da Vinci",
      "Albert Einstein",
      "Isaac Newton",
      "Galileo Galilei",
      "Charles Darwin",
      "Nikola Tesla",
      "Marie Curie",
      "Abraham Lincoln",
      "Winston Churchill",
      "Genghis Khan",
      "Marco Polo",
      "Cristóbal Colón",
      "Martin Luther King",
      "Nelson Mandela",
      "Gandhi",
      "Simon Bolívar",
      "San Martín",
      "Fidel Castro",
      "Che Guevara",
      "Mozart",
      "Beethoven",
      "Shakespeare",
      "Cervantes",
      "Aristóteles",
      "Platón",
      "Sócrates",
      "Confucio",
      "Buda",
      "Juana de Arco",
      "Isaac Asimov",
      "Stephen Hawking",
      "Thomas Edison",
      "Henry Ford",
      "Steve Jobs",
      "Bill Gates",
      "Rosa Parks",
      "Anne Frank",
      "Eva Perón",
    ],
  },
  objetos: {
    label: "Objetos Cotidianos",
    icon: "🪑",
    words: [
      "Silla",
      "Mesa",
      "Televisor",
      "Teléfono",
      "Computadora",
      "Refrigerador",
      "Lavadora",
      "Microondas",
      "Cama",
      "Almohada",
      "Espejo",
      "Reloj",
      "Lámpara",
      "Ventilador",
      "Aspiradora",
      "Cafetera",
      "Tostadora",
      "Licuadora",
      "Plancha",
      "Tijeras",
      "Martillo",
      "Destornillador",
      "Paraguas",
      "Mochila",
      "Maleta",
      "Billetera",
      "Bolígrafo",
      "Cuaderno",
      "Zapatos",
      "Gafas de sol",
      "Taza",
      "Vaso",
      "Plato",
      "Olla",
      "Sartén",
      "Cuchillo",
      "Tabla de cortar",
      "Control remoto",
      "Cargador de celular",
      "Auriculares",
      "Escoba",
      "Balde",
      "Toalla",
      "Almohadón",
      "Frazada",
      "Colgador de ropa",
      "Linterna",
      "Vela",
      "Fósforos",
      "Candado",
      "Llavero",
    ],
  },
  animales: {
    label: "Animales",
    icon: "🦁",
    words: [
      "León",
      "Tigre",
      "Elefante",
      "Jirafa",
      "Hipopótamo",
      "Rinoceronte",
      "Cebra",
      "Gorila",
      "Delfín",
      "Ballena",
      "Tiburón",
      "Pulpo",
      "Tortuga marina",
      "Águila",
      "Pingüino",
      "Flamenco",
      "Pavo real",
      "Colibrí",
      "Búho",
      "Perro",
      "Gato",
      "Conejo",
      "Panda",
      "Koala",
      "Canguro",
      "Ornitorrinco",
      "Anaconda",
      "Cobra",
      "Camaleón",
      "Caballo",
      "Vaca",
      "Cerdo",
      "Oveja",
      "Camello",
      "Axolotl",
      "Lobo",
      "Zorro",
      "Oso",
      "Oso polar",
      "Mapache",
      "Ardilla",
      "Erizo",
      "Murciélago",
      "Rana",
      "Sapo",
      "Lagarto",
      "Cocodrilo",
      "Buitre",
      "Cisne",
      "Pato",
      "Loro",
      "Hormiga",
      "Abeja",
      "Mariposa",
      "Araña",
      "Escorpión",
      "Medusa",
      "Estrella de mar",
      "Cangrejo",
      "Langosta",
    ],
  },
  paises: {
    label: "Países del Mundo",
    icon: "🌍",
    words: [
      "China",
      "India",
      "Estados Unidos",
      "Indonesia",
      "Brasil",
      "Nigeria",
      "Japón",
      "Egipto",
      "Alemania",
      "Francia",
      "Reino Unido",
      "España",
      "Italia",
      "Argentina",
      "Colombia",
      "Canadá",
      "Australia",
      "Corea del Sur",
      "Arabia Saudita",
      "Sudáfrica",
      "Marruecos",
      "Suecia",
      "Noruega",
      "Dinamarca",
      "Finlandia",
      "Suiza",
      "Austria",
      "Bélgica",
      "Polonia",
      "Perú",
      "Chile",
      "Ecuador",
      "Bolivia",
      "Cuba",
      "Jamaica",
      "Portugal",
      "Grecia",
      "Turquía",
      "Rusia",
      "Ucrania",
      "Nueva Zelanda",
      "Tailandia",
      "Vietnam",
      "Filipinas",
      "Malasia",
      "Singapur",
      "Kenia",
      "Etiopía",
      "Islandia",
      "Irlanda",
      "Croacia",
    ],
  },
  comidas: {
    label: "Comidas del Mundo",
    icon: "🍕",
    words: [
      "Pizza",
      "Sushi",
      "Tacos",
      "Ramen",
      "Paella",
      "Spaghetti",
      "Hamburguesa",
      "Asado",
      "Empanadas",
      "Ceviche",
      "Arepas",
      "Tamales",
      "Enchiladas",
      "Churros",
      "Croissant",
      "Fondue",
      "Gyros",
      "Falafel",
      "Hummus",
      "Shawarma",
      "Curry",
      "Pad Thai",
      "Pho",
      "Bibimbap",
      "Kimchi",
      "Dim Sum",
      "Mole",
      "Locro",
      "Carbonada",
      "Milanesa",
      "Choripán",
      "Alfajores",
      "Feijoada",
      "Brigadeiro",
      "Dulce de leche",
      "Milkshake",
      "Helado",
      "Panqueques",
      "Waffles",
      "Bruschetta",
      "Lasaña",
      "Risotto",
      "Gnocchi",
      "Kebab",
      "Baklava",
      "Goulash",
      "Fish and chips",
      "Poutine",
      "Nachos",
      "Guacamole",
      "Quesadilla",
    ],
  },
  deportes: {
    label: "Deportes",
    icon: "🏅",
    words: [
      "Fútbol",
      "Basketball",
      "Tenis",
      "Natación",
      "Atletismo",
      "Boxeo",
      "Ciclismo",
      "Golf",
      "Rugby",
      "Béisbol",
      "Volleyball",
      "Handball",
      "Hockey sobre hielo",
      "Esquí",
      "Snowboard",
      "Surf",
      "Escalada",
      "Triatlón",
      "Esgrima",
      "Judo",
      "Karate",
      "Taekwondo",
      "Lucha libre",
      "Halterofilia",
      "Gimnasia artística",
      "Patinaje artístico",
      "Polo",
      "Tiro con arco",
      "Vela",
      "Squash",
      "Padel",
      "Cricket",
      "Bowling",
      "Billar",
      "Ajedrez",
      "Automovilismo",
      "Motociclismo",
      "Remo",
      "Skateboarding",
      "Motocross",
      "Softbol",
      "Waterpolo",
      "Curling",
      "Bádminton",
    ],
  },
  musicos: {
    label: "Músicos Famosos",
    icon: "🎸",
    words: [
      "Michael Jackson",
      "Elvis Presley",
      "The Beatles",
      "Queen",
      "Rolling Stones",
      "Led Zeppelin",
      "Pink Floyd",
      "David Bowie",
      "Bob Dylan",
      "Jimi Hendrix",
      "Madonna",
      "Whitney Houston",
      "Beyoncé",
      "Rihanna",
      "Shakira",
      "Taylor Swift",
      "Ariana Grande",
      "Lady Gaga",
      "Adele",
      "Ed Sheeran",
      "Bruno Mars",
      "The Weeknd",
      "Eminem",
      "Jay-Z",
      "Kanye West",
      "Drake",
      "Bad Bunny",
      "J Balvin",
      "Daddy Yankee",
      "Luis Fonsi",
      "Celia Cruz",
      "Julio Iglesias",
      "Chayanne",
      "Ricky Martin",
      "Gloria Estefan",
      "Karol G",
      "Maluma",
      "Ozuna",
      "Feid",
      "Peso Pluma",
      "Rosalía",
      "Charly García",
      "Gustavo Cerati",
      "Fito Páez",
      "Luis Miguel",
      "Selena Quintanilla",
      "Juan Gabriel",
      "Vicente Fernández",
      "Frank Sinatra",
      "Freddie Mercury",
      "John Lennon",
      "Paul McCartney",
    ],
  },
  superheroes: {
    label: "Superhéroes y Villanos",
    icon: "🦸",
    words: [
      "Superman",
      "Batman",
      "Spider-Man",
      "Iron Man",
      "Capitán América",
      "Thor",
      "Hulk",
      "Wonder Woman",
      "Flash",
      "Aquaman",
      "Linterna Verde",
      "Black Widow",
      "Doctor Strange",
      "Pantera Negra",
      "Capitana Marvel",
      "Deadpool",
      "Wolverine",
      "Profesor X",
      "Mystique",
      "Joker",
      "Lex Luthor",
      "Thanos",
      "Loki",
      "Venom",
      "Magneto",
      "Guasón",
      "Harley Quinn",
      "Darkseid",
    ],
  },
  videojuegos: {
    label: "Videojuegos",
    icon: "🎮",
    words: [
      "Minecraft",
      "Fortnite",
      "Among Us",
      "The Legend of Zelda",
      "Super Mario Bros",
      "Grand Theft Auto",
      "Call of Duty",
      "FIFA",
      "The Last of Us",
      "God of War",
      "Red Dead Redemption",
      "Pokémon",
      "Animal Crossing",
      "League of Legends",
      "Valorant",
      "Counter-Strike",
      "Fall Guys",
      "Roblox",
      "Tetris",
      "Sonic",
      "Street Fighter",
      "Mortal Kombat",
      "The Sims",
      "Overwatch",
      "Halo",
      "Resident Evil",
      "Elden Ring",
      "Genshin Impact",
    ],
  },
  peliculas: {
    label: "Películas Famosas",
    icon: "🎥",
    words: [
      "Titanic",
      "El Padrino",
      "Star Wars",
      "Jurassic Park",
      "El Señor de los Anillos",
      "Harry Potter",
      "Avatar",
      "Los Vengadores",
      "El Rey León",
      "Forrest Gump",
      "Matrix",
      "Pulp Fiction",
      "El Origen",
      "Interestelar",
      "Coco",
      "Frozen",
      "Toy Story",
      "Shrek",
      "Joker",
      "Parásitos",
      "La La Land",
      "Gladiador",
      "Rocky",
      "Volver al Futuro",
      "Jaws",
      "E.T.",
      "Los Increíbles",
    ],
  },
  series: {
    label: "Series de TV",
    icon: "📺",
    words: [
      "Friends",
      "Breaking Bad",
      "Game of Thrones",
      "Stranger Things",
      "The Office",
      "La Casa de Papel",
      "Los Simpson",
      "Grey's Anatomy",
      "How I Met Your Mother",
      "The Walking Dead",
      "Peaky Blinders",
      "Narcos",
      "Black Mirror",
      "The Crown",
      "Better Call Saul",
      "Sherlock",
      "Dark",
      "Élite",
      "Vikingos",
      "El Chavo del 8",
      "Rick and Morty",
      "South Park",
      "Bob Esponja",
      "Euphoria",
      "Wednesday",
    ],
  },
  profesiones: {
    label: "Profesiones",
    icon: "💼",
    words: [
      "Médico",
      "Enfermero",
      "Bombero",
      "Policía",
      "Abogado",
      "Maestro",
      "Ingeniero",
      "Arquitecto",
      "Piloto",
      "Chef",
      "Peluquero",
      "Electricista",
      "Plomero",
      "Carpintero",
      "Veterinario",
      "Psicólogo",
      "Periodista",
      "Fotógrafo",
      "Actor",
      "Músico",
      "Programador",
      "Contador",
      "Dentista",
      "Farmacéutico",
      "Albañil",
      "Panadero",
      "Mecánico",
      "Astronauta",
    ],
  },
  marcas: {
    label: "Marcas Famosas",
    icon: "🏷️",
    words: [
      "Coca-Cola",
      "Pepsi",
      "McDonald's",
      "Nike",
      "Adidas",
      "Apple",
      "Samsung",
      "Google",
      "Amazon",
      "Netflix",
      "Disney",
      "Ferrari",
      "Toyota",
      "BMW",
      "Starbucks",
      "IKEA",
      "Gucci",
      "Chanel",
      "Rolex",
      "Lego",
      "Sony",
      "Nintendo",
      "PlayStation",
      "Xbox",
      "Instagram",
      "WhatsApp",
      "TikTok",
    ],
  },
  lugares: {
    label: "Lugares Turísticos",
    icon: "🗺️",
    words: [
      "Torre Eiffel",
      "Coliseo Romano",
      "Machu Picchu",
      "Gran Muralla China",
      "Taj Mahal",
      "Cataratas del Iguazú",
      "Estatua de la Libertad",
      "Torre de Pisa",
      "Sagrada Familia",
      "Big Ben",
      "Cristo Redentor",
      "Pirámides de Egipto",
      "Times Square",
      "Las Vegas",
      "Disneyland",
      "Chichén Itzá",
      "Salar de Uyuni",
      "Islas Galápagos",
      "Gran Cañón",
      "Muralla de Berlín",
      "Kremlin",
      "Ópera de Sídney",
      "Monte Everest",
      "Amazonas",
    ],
  },
};
