// ─── Game Data ───────────────────────────────────────────────────────────────
export interface Category {
  label: string;
  icon: string;
  words: string[];
  // Per-word hint shown only to the impostor (if the host enables hints) —
  // a deliberately vague clue that fits many entries in the category, so it
  // helps them bluff a little without giving away which word it actually is.
  hints: Record<string, string>;
}

export const CATEGORIES: Record<string, Category> = {
  futbolistas: {
    label: "Jugadores de Fútbol",
    icon: "⚽",
    hints: {
      Messi: "Se movía por arriba o por las bandas, cerca del gol",
      "Cristiano Ronaldo": "Se movía por arriba o por las bandas, cerca del gol",
      Neymar: "Se movía por arriba o por las bandas, cerca del gol",
      Mbappé: "Se mueve por arriba o por las bandas, cerca del gol",
      Haaland: "Su terreno es el área rival",
      Benzema: "Su terreno era el área rival",
      Lewandowski: "Su terreno es el área rival",
      Salah: "Se mueve por arriba o por las bandas, cerca del gol",
      "De Bruyne": "Se lo ve en el medio, repartiendo juego",
      Modric: "Se lo ve en el medio, repartiendo juego",
      "Vinicius Jr": "Se mueve por arriba o por las bandas, cerca del gol",
      Pedri: "Se lo ve en el medio, repartiendo juego",
      Gavi: "Se lo ve en el medio, repartiendo juego",
      Bellingham: "Se lo ve en el medio, repartiendo juego",
      "Lautaro Martínez": "Su terreno es el área rival",
      Álvarez: "Su terreno es el área rival",
      Dybala: "Se mueve por arriba o por las bandas, cerca del gol",
      "Di María": "Alterna entre la banda y armar juego",
      Rooney: "Su terreno era el área rival",
      Gerrard: "Se lo veía en el medio, repartiendo juego",
      Lampard: "Se lo veía en el medio, repartiendo juego",
      Beckham: "Se lo veía en el medio, repartiendo juego",
      Henry: "Su terreno era el área rival",
      Zidane: "Se lo veía en el medio, repartiendo juego",
      Ronaldinho: "Se movía por arriba o por las bandas, cerca del gol",
      Maradona: "Alternaba entre la ofensiva y armar juego",
      Pelé: "Su terreno era el área rival",
      Buffon: "Pasó su carrera bajo los tres palos",
      Casillas: "Pasó su carrera bajo los tres palos",
      Neuer: "Pasa su carrera bajo los tres palos",
      "Ter Stegen": "Pasa su carrera bajo los tres palos",
      "De Gea": "Pasa su carrera bajo los tres palos",
      Oblak: "Pasa su carrera bajo los tres palos",
      Courtois: "Pasa su carrera bajo los tres palos",
      Alisson: "Pasa su carrera bajo los tres palos",
      Ramos: "Su trabajo era frenar al que atacaba",
      Piqué: "Su trabajo era frenar al que atacaba",
      Varane: "Su trabajo es frenar al que ataca",
      "Trent Alexander-Arnold": "Su trabajo es frenar al que ataca",
      Marcelo: "Su trabajo era frenar al que atacaba",
      Griezmann: "Su terreno es el área rival",
      Suárez: "Su terreno era el área rival",
      Cavani: "Su terreno era el área rival",
      Agüero: "Su terreno era el área rival",
      Higuaín: "Su terreno era el área rival",
      Tevez: "Su terreno era el área rival",
      Riquelme: "Se lo veía en el medio, repartiendo juego",
      Verón: "Se lo veía en el medio, repartiendo juego",
      Kaká: "Se lo veía en el medio, repartiendo juego",
      Iniesta: "Se lo veía en el medio, repartiendo juego",
      Xavi: "Se lo veía en el medio, repartiendo juego",
      Puyol: "Su trabajo era frenar al que atacaba",
      "Van Dijk": "Su trabajo es frenar al que ataca",
      Kanté: "Se lo ve en el medio, repartiendo juego",
      Pogba: "Se lo ve en el medio, repartiendo juego",
    },
    words: [
      "Messi",
      "Cristiano Ronaldo",
      "Neymar",
      "Mbappé",
      "Haaland",
      "Benzema",
      "Lewandowski",
      "Salah",
      "De Bruyne",
      "Modric",
      "Vinicius Jr",
      "Pedri",
      "Gavi",
      "Bellingham",
      "Lautaro Martínez",
      "Álvarez",
      "Dybala",
      "Di María",
      "Rooney",
      "Gerrard",
      "Lampard",
      "Beckham",
      "Henry",
      "Zidane",
      "Ronaldinho",
      "Maradona",
      "Pelé",
      "Buffon",
      "Casillas",
      "Neuer",
      "Ter Stegen",
      "De Gea",
      "Oblak",
      "Courtois",
      "Alisson",
      "Ramos",
      "Piqué",
      "Varane",
      "Trent Alexander-Arnold",
      "Marcelo",
      "Griezmann",
      "Suárez",
      "Cavani",
      "Agüero",
      "Higuaín",
      "Tevez",
      "Riquelme",
      "Verón",
      "Kaká",
      "Iniesta",
      "Xavi",
      "Puyol",
      "Van Dijk",
      "Kanté",
      "Pogba",
    ],
  },
  selecciones: {
    label: "Selecciones de Fútbol",
    icon: "🏆",
    hints: {
      Argentina: "Queda en Sudamérica",
      Brasil: "Queda en Sudamérica",
      Francia: "Pertenece al continente europeo",
      Alemania: "Pertenece al continente europeo",
      España: "Pertenece al continente europeo",
      Portugal: "Pertenece al continente europeo",
      Italia: "Pertenece al continente europeo",
      Inglaterra: "El inglés es su idioma principal",
      "Países Bajos": "Pertenece al continente europeo",
      Bélgica: "Pertenece al continente europeo",
      Uruguay: "Queda en Sudamérica",
      Colombia: "Queda en Sudamérica",
      México: "Se ubica en Norteamérica o Centroamérica",
      Japón: "Se ubica en Asia",
      Senegal: "Forma parte del continente africano",
      Marruecos: "Forma parte del continente africano",
      Ghana: "Forma parte del continente africano",
      Ecuador: "Queda en Sudamérica",
      Perú: "Queda en Sudamérica",
      Chile: "Queda en Sudamérica",
      Paraguay: "Queda en Sudamérica",
      Australia: "El inglés es su idioma principal",
      Croacia: "Pertenece al continente europeo",
      Suiza: "Pertenece al continente europeo",
      Dinamarca: "Pertenece al continente europeo",
      Polonia: "Pertenece al continente europeo",
      Suecia: "Pertenece al continente europeo",
      Serbia: "Pertenece al continente europeo",
      Turquía: "Se extiende entre Europa y Asia",
      Ucrania: "Pertenece al continente europeo",
      "Costa Rica": "Se ubica en Norteamérica o Centroamérica",
      Panamá: "Se ubica en Norteamérica o Centroamérica",
      Venezuela: "Queda en Sudamérica",
      Túnez: "Forma parte del continente africano",
      Argelia: "Forma parte del continente africano",
      Camerún: "Forma parte del continente africano",
      Nigeria: "Forma parte del continente africano",
      Irán: "Se ubica en Asia",
      "Arabia Saudita": "Se ubica en Asia",
      Catar: "Se ubica en Asia",
      "Corea del Sur": "Se ubica en Asia",
      "Estados Unidos": "El inglés es su idioma principal",
      Canadá: "El inglés es su idioma principal",
      Gales: "El inglés es su idioma principal",
      Escocia: "El inglés es su idioma principal",
    },
    words: [
      "Argentina",
      "Brasil",
      "Francia",
      "Alemania",
      "España",
      "Portugal",
      "Italia",
      "Inglaterra",
      "Países Bajos",
      "Bélgica",
      "Uruguay",
      "Colombia",
      "México",
      "Japón",
      "Senegal",
      "Marruecos",
      "Ghana",
      "Ecuador",
      "Perú",
      "Chile",
      "Paraguay",
      "Australia",
      "Croacia",
      "Suiza",
      "Dinamarca",
      "Polonia",
      "Suecia",
      "Serbia",
      "Turquía",
      "Ucrania",
      "Costa Rica",
      "Panamá",
      "Venezuela",
      "Túnez",
      "Argelia",
      "Camerún",
      "Nigeria",
      "Irán",
      "Arabia Saudita",
      "Catar",
      "Corea del Sur",
      "Estados Unidos",
      "Canadá",
      "Gales",
      "Escocia",
    ],
  },
  actores: {
    label: "Actores Famosos",
    icon: "🎬",
    hints: {
      "Tom Hanks": "Suele quedarse con los papeles más serios",
      "Brad Pitt": "Combina acción y drama en su filmografía",
      "Leonardo DiCaprio": "Suele quedarse con los papeles más serios",
      "Angelina Jolie": "Combina acción y drama en su filmografía",
      "Meryl Streep": "Suele quedarse con los papeles más serios",
      "Scarlett Johansson": "Pasó también por el cine de superhéroes",
      "Robert Downey Jr": "Pasó también por el cine de superhéroes",
      "Johnny Depp": "Elige personajes fuera de lo común",
      "Will Smith": "También canta, no solo actúa",
      "Denzel Washington": "Suele quedarse con los papeles más serios",
      "Morgan Freeman": "Su voz es tan reconocible como su actuación",
      "Anthony Hopkins": "Suele quedarse con los papeles más serios",
      "Cate Blanchett": "Suele quedarse con los papeles más serios",
      "Natalie Portman": "Pasó también por la fantasía o la ciencia ficción",
      "Julia Roberts": "Brilla sobre todo en la comedia romántica",
      "Jennifer Aniston": "Se la asocia sobre todo con la comedia",
      "Sandra Bullock": "Reparte su carrera entre comedia y drama",
      "Nicole Kidman": "Suele quedarse con los papeles más serios",
      "Ryan Reynolds": "Pasó también por el cine de superhéroes",
      "Ryan Gosling": "Reparte su carrera entre drama y comedia romántica",
      "Chris Evans": "Pasó también por el cine de superhéroes",
      "Chris Hemsworth": "Pasó también por el cine de superhéroes",
      "Dwayne Johnson": "Antes de actuar tuvo una carrera deportiva",
      "Keanu Reeves": "Se lo asocia sobre todo con el cine de acción",
      "Joaquin Phoenix": "Suele quedarse con los papeles más serios",
      "Tom Cruise": "Se lo asocia sobre todo con el cine de acción",
      "Harrison Ford": "Se lo asocia con la acción y la aventura",
      "Al Pacino": "Suele quedarse con los papeles más serios",
      "Robert De Niro": "Suele quedarse con los papeles más serios",
      "Jack Nicholson": "Suele quedarse con los papeles más serios",
      "Penélope Cruz": "Suele quedarse con los papeles más serios",
      "Antonio Banderas": "También le puso voz a personajes animados",
      "Salma Hayek": "Reparte su carrera entre drama y comedia",
      "Emma Watson": "Se hizo famosa siendo muy joven",
      "Emma Stone": "Reparte su carrera entre comedia y drama",
      "Margot Robbie": "Pasó también por el cine de superhéroes",
      Zendaya: "Se hizo famosa siendo muy joven",
      "Timothée Chalamet": "Es joven y ya se lo asocia con papeles serios",
      "Tom Holland": "Pasó también por el cine de superhéroes",
      "Robert Pattinson": "Pasó también por el cine de superhéroes",
      "Jason Momoa": "Pasó también por el cine de superhéroes",
      "Gal Gadot": "Pasó también por el cine de superhéroes",
      "Charlize Theron": "Combina acción y drama en su filmografía",
      "Hugh Jackman": "Pasó también por el cine de superhéroes",
      "Samuel L. Jackson": "Pasó también por el cine de superhéroes",
      "Matthew McConaughey": "Reparte su carrera entre drama y comedia romántica",
      "Christian Bale": "Pasó también por el cine de superhéroes",
    },
    words: [
      "Tom Hanks",
      "Brad Pitt",
      "Leonardo DiCaprio",
      "Angelina Jolie",
      "Meryl Streep",
      "Scarlett Johansson",
      "Robert Downey Jr",
      "Johnny Depp",
      "Will Smith",
      "Denzel Washington",
      "Morgan Freeman",
      "Anthony Hopkins",
      "Cate Blanchett",
      "Natalie Portman",
      "Julia Roberts",
      "Jennifer Aniston",
      "Sandra Bullock",
      "Nicole Kidman",
      "Ryan Reynolds",
      "Ryan Gosling",
      "Chris Evans",
      "Chris Hemsworth",
      "Dwayne Johnson",
      "Keanu Reeves",
      "Joaquin Phoenix",
      "Tom Cruise",
      "Harrison Ford",
      "Al Pacino",
      "Robert De Niro",
      "Jack Nicholson",
      "Penélope Cruz",
      "Antonio Banderas",
      "Salma Hayek",
      "Emma Watson",
      "Emma Stone",
      "Margot Robbie",
      "Zendaya",
      "Timothée Chalamet",
      "Tom Holland",
      "Robert Pattinson",
      "Jason Momoa",
      "Gal Gadot",
      "Charlize Theron",
      "Hugh Jackman",
      "Samuel L. Jackson",
      "Matthew McConaughey",
      "Christian Bale",
    ],
  },
  historicos: {
    label: "Personajes Históricos",
    icon: "📜",
    hints: {
      "Napoleón Bonaparte": "Se destacó en la política o al mando de un ejército",
      "Julio César": "Perteneció a la antigüedad",
      "Alejandro Magno": "Perteneció a la antigüedad",
      Cleopatra: "Perteneció a la antigüedad",
      "Leonardo Da Vinci": "Dejó huella en el arte o el pensamiento",
      "Albert Einstein": "Su aporte fue en el campo de la ciencia",
      "Isaac Newton": "Su aporte fue en el campo de la ciencia",
      "Galileo Galilei": "Su aporte fue en el campo de la ciencia",
      "Charles Darwin": "Su aporte fue en el campo de la ciencia",
      "Nikola Tesla": "Su aporte fue en ciencia o tecnología",
      "Marie Curie": "Su aporte fue en el campo de la ciencia",
      "Abraham Lincoln": "Ocupó un rol de gobierno o liderazgo político",
      "Winston Churchill": "Ocupó un rol de gobierno o liderazgo político",
      "Genghis Khan": "Perteneció a la época medieval",
      "Marco Polo": "Perteneció a la época medieval",
      "Cristóbal Colón": "Perteneció a la época medieval",
      "Martin Luther King": "Se lo recuerda por su lucha política o por los derechos civiles",
      "Nelson Mandela": "Se lo recuerda por su lucha política o por los derechos civiles",
      Gandhi: "Se lo recuerda por su lucha política o por los derechos civiles",
      "Simon Bolívar": "Se destacó en la política o al mando de un ejército",
      "San Martín": "Se destacó en la política o al mando de un ejército",
      "Fidel Castro": "Ocupó un rol de gobierno o liderazgo político",
      "Che Guevara": "Se destacó en la política o al mando de un ejército",
      Mozart: "Dejó huella en el arte o el pensamiento",
      Beethoven: "Dejó huella en el arte o el pensamiento",
      Shakespeare: "Dejó huella en el arte o el pensamiento",
      Cervantes: "Dejó huella en el arte o el pensamiento",
      Aristóteles: "Perteneció a la antigüedad",
      Platón: "Perteneció a la antigüedad",
      Sócrates: "Perteneció a la antigüedad",
      Confucio: "Perteneció a la antigüedad",
      Buda: "Perteneció a la antigüedad",
      "Juana de Arco": "Perteneció a la época medieval",
      "Isaac Asimov": "Su aporte fue en ciencia o en literatura",
      "Stephen Hawking": "Su aporte fue en el campo de la ciencia",
      "Thomas Edison": "Su aporte fue en ciencia o tecnología",
      "Henry Ford": "Dejó marca en la industria o la tecnología",
      "Steve Jobs": "Dejó marca en el mundo de la tecnología",
      "Bill Gates": "Dejó marca en el mundo de la tecnología",
      "Rosa Parks": "Se lo recuerda por su lucha política o por los derechos civiles",
      "Anne Frank": "Perteneció al siglo XX",
      "Eva Perón": "Se lo recuerda por su rol político",
    },
    words: [
      "Napoleón Bonaparte",
      "Julio César",
      "Alejandro Magno",
      "Cleopatra",
      "Leonardo Da Vinci",
      "Albert Einstein",
      "Isaac Newton",
      "Galileo Galilei",
      "Charles Darwin",
      "Nikola Tesla",
      "Marie Curie",
      "Abraham Lincoln",
      "Winston Churchill",
      "Genghis Khan",
      "Marco Polo",
      "Cristóbal Colón",
      "Martin Luther King",
      "Nelson Mandela",
      "Gandhi",
      "Simon Bolívar",
      "San Martín",
      "Fidel Castro",
      "Che Guevara",
      "Mozart",
      "Beethoven",
      "Shakespeare",
      "Cervantes",
      "Aristóteles",
      "Platón",
      "Sócrates",
      "Confucio",
      "Buda",
      "Juana de Arco",
      "Isaac Asimov",
      "Stephen Hawking",
      "Thomas Edison",
      "Henry Ford",
      "Steve Jobs",
      "Bill Gates",
      "Rosa Parks",
      "Anne Frank",
      "Eva Perón",
    ],
  },
  objetos: {
    label: "Objetos Cotidianos",
    icon: "🪑",
    hints: {
      Silla: "Forma parte del mobiliario de una casa",
      Mesa: "Forma parte del mobiliario de una casa",
      Televisor: "Necesita enchufarse o tener pilas para funcionar",
      Teléfono: "Necesita enchufarse o tener pilas para funcionar",
      Computadora: "Necesita enchufarse o tener pilas para funcionar",
      Refrigerador: "Se lo encuentra habitualmente en la cocina",
      Lavadora: "Necesita enchufarse o tener pilas para funcionar",
      Microondas: "Se lo encuentra habitualmente en la cocina",
      Cama: "Forma parte del mobiliario de una casa",
      Almohada: "Está pensado para el descanso",
      Espejo: "Es común encontrarlo en un dormitorio",
      Reloj: "Sirve para consultar la hora",
      Lámpara: "Necesita enchufarse o tener pilas para funcionar",
      Ventilador: "Necesita enchufarse o tener pilas para funcionar",
      Aspiradora: "Necesita enchufarse o tener pilas para funcionar",
      Cafetera: "Se lo encuentra habitualmente en la cocina",
      Tostadora: "Se lo encuentra habitualmente en la cocina",
      Licuadora: "Se lo encuentra habitualmente en la cocina",
      Plancha: "Necesita enchufarse o tener pilas para funcionar",
      Tijeras: "Es una herramienta que corta",
      Martillo: "Se usa para arreglar o construir cosas",
      Destornillador: "Se usa para arreglar o construir cosas",
      Paraguas: "Se lo saca solo de vez en cuando",
      Mochila: "Sirve para cargar cosas de un lado a otro",
      Maleta: "Sirve para cargar cosas de un lado a otro",
      Billetera: "Se lo lleva siempre al salir",
      Bolígrafo: "Sirve para escribir o anotar",
      Cuaderno: "Sirve para escribir o anotar",
      Zapatos: "Se lo usa afuera, no adentro de la casa",
      "Gafas de sol": "Se lo usa afuera, no adentro de la casa",
      Taza: "Se lo encuentra habitualmente en la cocina",
      Vaso: "Se lo encuentra habitualmente en la cocina",
      Plato: "Se lo encuentra habitualmente en la cocina",
      Olla: "Se lo encuentra habitualmente en la cocina",
      Sartén: "Se lo encuentra habitualmente en la cocina",
      Cuchillo: "Se lo encuentra habitualmente en la cocina",
      "Tabla de cortar": "Se lo encuentra habitualmente en la cocina",
      "Control remoto": "Necesita pilas o electricidad para andar",
      "Cargador de celular": "Necesita enchufarse o tener pilas para funcionar",
      Auriculares: "Necesita enchufarse o tener pilas para funcionar",
      Escoba: "Se usa a la hora de limpiar la casa",
      Balde: "Se usa a la hora de limpiar la casa",
      Toalla: "Se usa para el aseo personal, no para limpiar la casa",
      Almohadón: "Es común encontrarlo en un dormitorio",
      Frazada: "Está pensado para el descanso",
      "Colgador de ropa": "Es un elemento pensado para el hogar",
      Linterna: "Se lo saca solo de vez en cuando",
      Vela: "Se lo saca solo de vez en cuando",
      Fósforos: "Se lo saca solo de vez en cuando",
      Candado: "Se lo saca solo de vez en cuando",
      Llavero: "Se lo lleva siempre al salir",
    },
    words: [
      "Silla",
      "Mesa",
      "Televisor",
      "Teléfono",
      "Computadora",
      "Refrigerador",
      "Lavadora",
      "Microondas",
      "Cama",
      "Almohada",
      "Espejo",
      "Reloj",
      "Lámpara",
      "Ventilador",
      "Aspiradora",
      "Cafetera",
      "Tostadora",
      "Licuadora",
      "Plancha",
      "Tijeras",
      "Martillo",
      "Destornillador",
      "Paraguas",
      "Mochila",
      "Maleta",
      "Billetera",
      "Bolígrafo",
      "Cuaderno",
      "Zapatos",
      "Gafas de sol",
      "Taza",
      "Vaso",
      "Plato",
      "Olla",
      "Sartén",
      "Cuchillo",
      "Tabla de cortar",
      "Control remoto",
      "Cargador de celular",
      "Auriculares",
      "Escoba",
      "Balde",
      "Toalla",
      "Almohadón",
      "Frazada",
      "Colgador de ropa",
      "Linterna",
      "Vela",
      "Fósforos",
      "Candado",
      "Llavero",
    ],
  },
  animales: {
    label: "Animales",
    icon: "🦁",
    hints: {
      León: "Es un mamífero grande que vive en tierra firme",
      Tigre: "Es un mamífero grande que vive en tierra firme",
      Elefante: "Es un mamífero grande que vive en tierra firme",
      Jirafa: "Es un mamífero grande que vive en tierra firme",
      Hipopótamo: "Es un mamífero grande que vive en tierra firme",
      Rinoceronte: "Es un mamífero grande que vive en tierra firme",
      Cebra: "Es un mamífero grande que vive en tierra firme",
      Gorila: "Es un mamífero grande que vive en tierra firme",
      Delfín: "Pasa la vida en el agua",
      Ballena: "Vive en el agua y es enorme",
      Tiburón: "Pasa la vida en el agua",
      Pulpo: "Pasa la vida en el agua",
      "Tortuga marina": "Pasa la vida en el agua",
      Águila: "Es capaz de volar",
      Pingüino: "Es un ave que no puede volar",
      Flamenco: "Pertenece al grupo de las aves",
      "Pavo real": "Pertenece al grupo de las aves",
      Colibrí: "Vuela y es de tamaño chico",
      Búho: "Es capaz de volar",
      Perro: "Suele tenerse como mascota",
      Gato: "Suele tenerse como mascota",
      Conejo: "Es un mamífero de tamaño chico",
      Panda: "Es un mamífero bastante grande",
      Koala: "Es un mamífero ni muy chico ni muy grande",
      Canguro: "Es un mamífero ni muy chico ni muy grande",
      Ornitorrinco: "No es un mamífero muy conocido",
      Anaconda: "Es un reptil que se arrastra, sin patas",
      Cobra: "Es un reptil que se arrastra, sin patas",
      Camaleón: "Pertenece al grupo de los reptiles",
      Caballo: "Se lo asocia con el campo",
      Vaca: "Se cría habitualmente en granjas",
      Cerdo: "Se cría habitualmente en granjas",
      Oveja: "Se cría habitualmente en granjas",
      Camello: "Es un mamífero bastante grande",
      Axolotl: "Pasa la vida en el agua",
      Lobo: "Es un mamífero salvaje que caza para comer",
      Zorro: "Es un mamífero salvaje que caza para comer",
      Oso: "Es un mamífero bastante grande",
      "Oso polar": "Es un mamífero bastante grande",
      Mapache: "Es un mamífero salvaje de tamaño chico",
      Ardilla: "Es un mamífero de tamaño chico",
      Erizo: "Es un mamífero de tamaño chico",
      Murciélago: "Es capaz de volar",
      Rana: "Se mueve tanto en el agua como en tierra",
      Sapo: "Se mueve tanto en el agua como en tierra",
      Lagarto: "Pertenece al grupo de los reptiles",
      Cocodrilo: "Se mueve tanto en el agua como en tierra",
      Buitre: "Es capaz de volar",
      Cisne: "Es un ave que pasa mucho tiempo en el agua",
      Pato: "Es un ave que pasa mucho tiempo en el agua",
      Loro: "Es capaz de volar",
      Hormiga: "Es un insecto diminuto",
      Abeja: "Es un insecto capaz de volar",
      Mariposa: "Es un insecto capaz de volar",
      Araña: "Tiene más de cuatro patas y no tiene columna",
      Escorpión: "Tiene más de cuatro patas y no tiene columna",
      Medusa: "Pasa la vida en el agua",
      "Estrella de mar": "Pasa la vida en el agua",
      Cangrejo: "Vive en el agua o muy cerca de la costa",
      Langosta: "Pasa la vida en el agua",
    },
    words: [
      "León",
      "Tigre",
      "Elefante",
      "Jirafa",
      "Hipopótamo",
      "Rinoceronte",
      "Cebra",
      "Gorila",
      "Delfín",
      "Ballena",
      "Tiburón",
      "Pulpo",
      "Tortuga marina",
      "Águila",
      "Pingüino",
      "Flamenco",
      "Pavo real",
      "Colibrí",
      "Búho",
      "Perro",
      "Gato",
      "Conejo",
      "Panda",
      "Koala",
      "Canguro",
      "Ornitorrinco",
      "Anaconda",
      "Cobra",
      "Camaleón",
      "Caballo",
      "Vaca",
      "Cerdo",
      "Oveja",
      "Camello",
      "Axolotl",
      "Lobo",
      "Zorro",
      "Oso",
      "Oso polar",
      "Mapache",
      "Ardilla",
      "Erizo",
      "Murciélago",
      "Rana",
      "Sapo",
      "Lagarto",
      "Cocodrilo",
      "Buitre",
      "Cisne",
      "Pato",
      "Loro",
      "Hormiga",
      "Abeja",
      "Mariposa",
      "Araña",
      "Escorpión",
      "Medusa",
      "Estrella de mar",
      "Cangrejo",
      "Langosta",
    ],
  },
  paises: {
    label: "Países del Mundo",
    icon: "🌍",
    hints: {
      China: "Se ubica en Asia",
      India: "Se ubica en Asia",
      "Estados Unidos": "Queda en Norteamérica",
      Indonesia: "Se ubica en Asia",
      Brasil: "Pertenece a Sudamérica",
      Nigeria: "Forma parte del continente africano",
      Japón: "Se ubica en Asia",
      Egipto: "Forma parte del continente africano",
      Alemania: "Está en el continente europeo",
      Francia: "Está en el continente europeo",
      "Reino Unido": "Está en el continente europeo",
      España: "Está en el continente europeo",
      Italia: "Está en el continente europeo",
      Argentina: "Pertenece a Sudamérica",
      Colombia: "Pertenece a Sudamérica",
      Canadá: "Queda en Norteamérica",
      Australia: "Pertenece a Oceanía",
      "Corea del Sur": "Se ubica en Asia",
      "Arabia Saudita": "Se ubica en Asia",
      Sudáfrica: "Forma parte del continente africano",
      Marruecos: "Forma parte del continente africano",
      Suecia: "Está en el continente europeo",
      Noruega: "Está en el continente europeo",
      Dinamarca: "Está en el continente europeo",
      Finlandia: "Está en el continente europeo",
      Suiza: "Está en el continente europeo",
      Austria: "Está en el continente europeo",
      Bélgica: "Está en el continente europeo",
      Polonia: "Está en el continente europeo",
      Perú: "Pertenece a Sudamérica",
      Chile: "Pertenece a Sudamérica",
      Ecuador: "Pertenece a Sudamérica",
      Bolivia: "Pertenece a Sudamérica",
      Cuba: "Se ubica en Centroamérica o el Caribe",
      Jamaica: "Se ubica en Centroamérica o el Caribe",
      Portugal: "Está en el continente europeo",
      Grecia: "Está en el continente europeo",
      Turquía: "Se extiende entre Europa y Asia",
      Rusia: "Se extiende entre Europa y Asia",
      Ucrania: "Está en el continente europeo",
      "Nueva Zelanda": "Pertenece a Oceanía",
      Tailandia: "Se ubica en Asia",
      Vietnam: "Se ubica en Asia",
      Filipinas: "Se ubica en Asia",
      Malasia: "Se ubica en Asia",
      Singapur: "Se ubica en Asia",
      Kenia: "Forma parte del continente africano",
      Etiopía: "Forma parte del continente africano",
      Islandia: "Está en el continente europeo",
      Irlanda: "Está en el continente europeo",
      Croacia: "Está en el continente europeo",
    },
    words: [
      "China",
      "India",
      "Estados Unidos",
      "Indonesia",
      "Brasil",
      "Nigeria",
      "Japón",
      "Egipto",
      "Alemania",
      "Francia",
      "Reino Unido",
      "España",
      "Italia",
      "Argentina",
      "Colombia",
      "Canadá",
      "Australia",
      "Corea del Sur",
      "Arabia Saudita",
      "Sudáfrica",
      "Marruecos",
      "Suecia",
      "Noruega",
      "Dinamarca",
      "Finlandia",
      "Suiza",
      "Austria",
      "Bélgica",
      "Polonia",
      "Perú",
      "Chile",
      "Ecuador",
      "Bolivia",
      "Cuba",
      "Jamaica",
      "Portugal",
      "Grecia",
      "Turquía",
      "Rusia",
      "Ucrania",
      "Nueva Zelanda",
      "Tailandia",
      "Vietnam",
      "Filipinas",
      "Malasia",
      "Singapur",
      "Kenia",
      "Etiopía",
      "Islandia",
      "Irlanda",
      "Croacia",
    ],
  },
  comidas: {
    label: "Comidas del Mundo",
    icon: "🍕",
    hints: {
      Pizza: "Es un plato salado que nació en Europa",
      Sushi: "Tiene raíces asiáticas",
      Tacos: "Es típico de la comida latinoamericana",
      Ramen: "Tiene raíces asiáticas",
      Paella: "Es un plato salado que nació en Europa",
      Spaghetti: "Es un plato salado que nació en Europa",
      Hamburguesa: "Se suele comer directamente con las manos",
      Asado: "Es típico de la comida latinoamericana",
      Empanadas: "Es típico de la comida latinoamericana",
      Ceviche: "Es típico de la comida latinoamericana",
      Arepas: "Es típico de la comida latinoamericana",
      Tamales: "Es típico de la comida latinoamericana",
      Enchiladas: "Es típico de la comida latinoamericana",
      Churros: "Es dulce, se come de postre",
      Croissant: "Nació en Europa",
      Fondue: "Tiene raíces europeas",
      Gyros: "Es típico de la cocina mediterránea",
      Falafel: "Es típico de la cocina mediterránea",
      Hummus: "Es típico de la cocina mediterránea",
      Shawarma: "Es típico de la cocina mediterránea",
      Curry: "Es un plato salado con raíces asiáticas",
      "Pad Thai": "Tiene raíces asiáticas",
      Pho: "Tiene raíces asiáticas",
      Bibimbap: "Tiene raíces asiáticas",
      Kimchi: "Tiene raíces asiáticas",
      "Dim Sum": "Tiene raíces asiáticas",
      Mole: "Es típico de la comida latinoamericana",
      Locro: "Es típico de la comida latinoamericana",
      Carbonada: "Es típico de la comida latinoamericana",
      Milanesa: "Es típico de la comida latinoamericana",
      Choripán: "Se suele comer directamente con las manos",
      Alfajores: "Es un postre típico de Latinoamérica",
      Feijoada: "Es típico de la comida latinoamericana",
      Brigadeiro: "Es un postre típico de Latinoamérica",
      "Dulce de leche": "Es un dulce típico de Latinoamérica",
      Milkshake: "Se toma o se come frío, y es dulce",
      Helado: "Se come frío y es dulce",
      Panqueques: "Es dulce, se come de postre",
      Waffles: "Es dulce, se come de postre",
      Bruschetta: "Es un plato salado que nació en Europa",
      Lasaña: "Es un plato salado que nació en Europa",
      Risotto: "Es un plato salado que nació en Europa",
      Gnocchi: "Es un plato salado que nació en Europa",
      Kebab: "Es típico de la cocina mediterránea",
      Baklava: "Es un postre típico del Mediterráneo",
      Goulash: "Es un plato salado que nació en Europa",
      "Fish and chips": "Es un plato salado que nació en Europa",
      Poutine: "Se puede comer con las manos o con tenedor",
      Nachos: "Es típico de la comida latinoamericana",
      Guacamole: "Es típico de la comida latinoamericana",
      Quesadilla: "Es típico de la comida latinoamericana",
    },
    words: [
      "Pizza",
      "Sushi",
      "Tacos",
      "Ramen",
      "Paella",
      "Spaghetti",
      "Hamburguesa",
      "Asado",
      "Empanadas",
      "Ceviche",
      "Arepas",
      "Tamales",
      "Enchiladas",
      "Churros",
      "Croissant",
      "Fondue",
      "Gyros",
      "Falafel",
      "Hummus",
      "Shawarma",
      "Curry",
      "Pad Thai",
      "Pho",
      "Bibimbap",
      "Kimchi",
      "Dim Sum",
      "Mole",
      "Locro",
      "Carbonada",
      "Milanesa",
      "Choripán",
      "Alfajores",
      "Feijoada",
      "Brigadeiro",
      "Dulce de leche",
      "Milkshake",
      "Helado",
      "Panqueques",
      "Waffles",
      "Bruschetta",
      "Lasaña",
      "Risotto",
      "Gnocchi",
      "Kebab",
      "Baklava",
      "Goulash",
      "Fish and chips",
      "Poutine",
      "Nachos",
      "Guacamole",
      "Quesadilla",
    ],
  },
  deportes: {
    label: "Deportes",
    icon: "🏅",
    hints: {
      Fútbol: "Se necesita un equipo y una pelota para jugarlo",
      Basketball: "Se necesita un equipo y una pelota para jugarlo",
      Tenis: "Se juega con pelota o raqueta, solo o en pareja",
      Natación: "Se practica dentro del agua",
      Atletismo: "No hace falta un equipo para practicarlo",
      Boxeo: "Enfrenta a dos rivales cuerpo a cuerpo",
      Ciclismo: "Se necesita algo con ruedas para practicarlo",
      Golf: "Se juega al aire libre con una pelota",
      Rugby: "Se necesita un equipo y una pelota para jugarlo",
      Béisbol: "Se necesita un equipo y una pelota para jugarlo",
      Volleyball: "Se necesita un equipo y una pelota para jugarlo",
      Handball: "Se necesita un equipo y una pelota para jugarlo",
      "Hockey sobre hielo": "Se practica arriba del hielo",
      Esquí: "Se necesita nieve para practicarlo",
      Snowboard: "Se necesita nieve para practicarlo",
      Surf: "Se practica dentro del agua",
      Escalada: "No hace falta un equipo para practicarlo",
      Triatlón: "Mezcla más de una disciplina deportiva",
      Esgrima: "Enfrenta a dos rivales cuerpo a cuerpo",
      Judo: "Enfrenta a dos rivales cuerpo a cuerpo",
      Karate: "Enfrenta a dos rivales cuerpo a cuerpo",
      Taekwondo: "Enfrenta a dos rivales cuerpo a cuerpo",
      "Lucha libre": "Enfrenta a dos rivales cuerpo a cuerpo",
      Halterofilia: "No hace falta un equipo para practicarlo",
      "Gimnasia artística": "No hace falta un equipo para practicarlo",
      "Patinaje artístico": "Se practica arriba del hielo",
      Polo: "Se juega con pelota montado en un vehículo o animal",
      "Tiro con arco": "No hace falta un equipo para practicarlo",
      Vela: "Se practica dentro del agua",
      Squash: "Requiere pelota y raqueta",
      Padel: "Requiere pelota y raqueta",
      Cricket: "Se necesita un equipo y una pelota para jugarlo",
      Bowling: "Se practica bajo techo",
      Billar: "Se practica bajo techo",
      Ajedrez: "Es más mental que físico",
      Automovilismo: "No se puede practicar sin un vehículo",
      Motociclismo: "No se puede practicar sin un vehículo",
      Remo: "Se practica dentro del agua",
      Skateboarding: "Se necesita algo con ruedas para practicarlo",
      Motocross: "No se puede practicar sin un vehículo",
      Softbol: "Se necesita un equipo y una pelota para jugarlo",
      Waterpolo: "Se practica dentro del agua",
      Curling: "Se practica arriba del hielo",
      Bádminton: "Requiere pelota y raqueta",
    },
    words: [
      "Fútbol",
      "Basketball",
      "Tenis",
      "Natación",
      "Atletismo",
      "Boxeo",
      "Ciclismo",
      "Golf",
      "Rugby",
      "Béisbol",
      "Volleyball",
      "Handball",
      "Hockey sobre hielo",
      "Esquí",
      "Snowboard",
      "Surf",
      "Escalada",
      "Triatlón",
      "Esgrima",
      "Judo",
      "Karate",
      "Taekwondo",
      "Lucha libre",
      "Halterofilia",
      "Gimnasia artística",
      "Patinaje artístico",
      "Polo",
      "Tiro con arco",
      "Vela",
      "Squash",
      "Padel",
      "Cricket",
      "Bowling",
      "Billar",
      "Ajedrez",
      "Automovilismo",
      "Motociclismo",
      "Remo",
      "Skateboarding",
      "Motocross",
      "Softbol",
      "Waterpolo",
      "Curling",
      "Bádminton",
    ],
  },
  musicos: {
    label: "Músicos Famosos",
    icon: "🎸",
    hints: {
      "Michael Jackson": "Hace carrera en solitario dentro del pop",
      "Elvis Presley": "Hizo carrera solo, en el rock o pop de otra época",
      "The Beatles": "Es un grupo, no un artista solista, dentro del rock",
      Queen: "Es un grupo, no un artista solista, dentro del rock",
      "Rolling Stones": "Es un grupo, no un artista solista, dentro del rock",
      "Led Zeppelin": "Es un grupo, no un artista solista, dentro del rock",
      "Pink Floyd": "Es un grupo, no un artista solista, dentro del rock",
      "David Bowie": "Hace carrera en solitario, entre el rock y el pop",
      "Bob Dylan": "Hace carrera solo, entre el rock y el folk",
      "Jimi Hendrix": "Hace carrera en solitario dentro del rock",
      Madonna: "Hace carrera en solitario dentro del pop",
      "Whitney Houston": "Hace carrera en solitario dentro del pop",
      Beyoncé: "Se mueve entre el pop y el R&B, en solitario",
      Rihanna: "Se mueve entre el pop y el R&B, en solitario",
      Shakira: "Hace carrera solista dentro del pop en español",
      "Taylor Swift": "Hace carrera en solitario dentro del pop",
      "Ariana Grande": "Hace carrera en solitario dentro del pop",
      "Lady Gaga": "Hace carrera en solitario dentro del pop",
      Adele: "Hace carrera en solitario dentro del pop",
      "Ed Sheeran": "Hace carrera en solitario dentro del pop",
      "Bruno Mars": "Hace carrera en solitario dentro del pop",
      "The Weeknd": "Se mueve entre el pop y el R&B, en solitario",
      Eminem: "Hace carrera en solitario dentro del rap",
      "Jay-Z": "Hace carrera en solitario dentro del rap",
      "Kanye West": "Hace carrera en solitario dentro del rap",
      Drake: "Se mueve entre el rap y el R&B, en solitario",
      "Bad Bunny": "Hace carrera solista dentro de la música urbana latina",
      "J Balvin": "Hace carrera solista dentro de la música urbana latina",
      "Daddy Yankee": "Hace carrera solista dentro de la música urbana latina",
      "Luis Fonsi": "Hace carrera solista dentro del pop en español",
      "Celia Cruz": "Hace carrera solista dentro de la música latina de otra época",
      "Julio Iglesias": "Hace carrera solista dentro de la música latina de otra época",
      Chayanne: "Hace carrera solista dentro del pop en español",
      "Ricky Martin": "Hace carrera solista dentro del pop en español",
      "Gloria Estefan": "Hace carrera solista dentro del pop en español",
      "Karol G": "Hace carrera solista dentro de la música urbana latina",
      Maluma: "Hace carrera solista dentro de la música urbana latina",
      Ozuna: "Hace carrera solista dentro de la música urbana latina",
      Feid: "Hace carrera solista dentro de la música urbana latina",
      "Peso Pluma": "Hace carrera solista dentro de la música urbana latina",
      Rosalía: "Se mueve entre el pop y la música urbana, en solitario",
      "Charly García": "Encabeza o encabezó una banda de rock en español",
      "Gustavo Cerati": "Encabeza o encabezó una banda de rock en español",
      "Fito Páez": "Hace carrera solista entre el rock y el pop en español",
      "Luis Miguel": "Hace carrera solista dentro de la música latina de otra época",
      "Selena Quintanilla": "Hace carrera solista dentro de la música latina de otra época",
      "Juan Gabriel": "Hace carrera solista dentro de la música latina de otra época",
      "Vicente Fernández": "Hace carrera solista dentro de la música latina de otra época",
      "Frank Sinatra": "Hace carrera solista dentro de la música anglosajona de otra época",
      "Freddie Mercury": "Formó parte de una banda de rock, no fue solista",
      "John Lennon": "Formó parte de una banda de rock, no fue solista",
      "Paul McCartney": "Formó parte de una banda de rock, no fue solista",
    },
    words: [
      "Michael Jackson",
      "Elvis Presley",
      "The Beatles",
      "Queen",
      "Rolling Stones",
      "Led Zeppelin",
      "Pink Floyd",
      "David Bowie",
      "Bob Dylan",
      "Jimi Hendrix",
      "Madonna",
      "Whitney Houston",
      "Beyoncé",
      "Rihanna",
      "Shakira",
      "Taylor Swift",
      "Ariana Grande",
      "Lady Gaga",
      "Adele",
      "Ed Sheeran",
      "Bruno Mars",
      "The Weeknd",
      "Eminem",
      "Jay-Z",
      "Kanye West",
      "Drake",
      "Bad Bunny",
      "J Balvin",
      "Daddy Yankee",
      "Luis Fonsi",
      "Celia Cruz",
      "Julio Iglesias",
      "Chayanne",
      "Ricky Martin",
      "Gloria Estefan",
      "Karol G",
      "Maluma",
      "Ozuna",
      "Feid",
      "Peso Pluma",
      "Rosalía",
      "Charly García",
      "Gustavo Cerati",
      "Fito Páez",
      "Luis Miguel",
      "Selena Quintanilla",
      "Juan Gabriel",
      "Vicente Fernández",
      "Frank Sinatra",
      "Freddie Mercury",
      "John Lennon",
      "Paul McCartney",
    ],
  },
  superheroes: {
    label: "Superhéroes y Villanos",
    icon: "🦸",
    hints: {
      Superman: "Tiene poderes fuera de lo normal",
      Batman: "No tiene poderes propios, se apoya en otra cosa",
      "Spider-Man": "Tiene poderes fuera de lo normal",
      "Iron Man": "No tiene poderes propios, se apoya en otra cosa",
      "Capitán América": "Sus capacidades físicas están potenciadas",
      Thor: "Tiene poderes fuera de lo normal",
      Hulk: "Tiene poderes fuera de lo normal",
      "Wonder Woman": "Tiene poderes fuera de lo normal",
      Flash: "Tiene poderes fuera de lo normal",
      Aquaman: "Tiene poderes fuera de lo normal",
      "Linterna Verde": "Tiene poderes fuera de lo normal",
      "Black Widow": "No tiene poderes propios, se apoya en otra cosa",
      "Doctor Strange": "Sus habilidades vienen de la magia",
      "Pantera Negra": "No tiene poderes propios, se apoya en otra cosa",
      "Capitana Marvel": "Tiene poderes fuera de lo normal",
      Deadpool: "Tiene poderes fuera de lo normal",
      Wolverine: "Tiene poderes fuera de lo normal",
      "Profesor X": "Tiene poderes fuera de lo normal",
      Mystique: "Cuenta con poderes fuera de lo normal",
      Joker: "Es un villano que no depende de poderes propios",
      "Lex Luthor": "Es un villano que no depende de poderes propios",
      Thanos: "Es un villano con poderes fuera de lo normal",
      Loki: "Sus poderes como villano vienen de la magia",
      Venom: "Es un villano con poderes fuera de lo normal",
      Magneto: "Es un villano con poderes fuera de lo normal",
      Guasón: "Es un villano que no depende de poderes propios",
      "Harley Quinn": "No cuenta con poderes propios",
      Darkseid: "Es un villano con poderes fuera de lo normal",
    },
    words: [
      "Superman",
      "Batman",
      "Spider-Man",
      "Iron Man",
      "Capitán América",
      "Thor",
      "Hulk",
      "Wonder Woman",
      "Flash",
      "Aquaman",
      "Linterna Verde",
      "Black Widow",
      "Doctor Strange",
      "Pantera Negra",
      "Capitana Marvel",
      "Deadpool",
      "Wolverine",
      "Profesor X",
      "Mystique",
      "Joker",
      "Lex Luthor",
      "Thanos",
      "Loki",
      "Venom",
      "Magneto",
      "Guasón",
      "Harley Quinn",
      "Darkseid",
    ],
  },
  videojuegos: {
    label: "Videojuegos",
    icon: "🎮",
    hints: {
      Minecraft: "Deja construir y explorar libremente",
      Fortnite: "Se juega en línea, a los tiros, contra otros",
      "Among Us": "Hay que descubrir a un impostor jugando en grupo",
      "The Legend of Zelda": "Mezcla aventura con exploración",
      "Super Mario Bros": "Hay que saltar entre plataformas para avanzar",
      "Grand Theft Auto": "Deja moverse libremente por un mundo abierto",
      "Call of Duty": "El objetivo pasa por disparar",
      FIFA: "Simula un deporte",
      "The Last of Us": "Tiene mucho peso en su historia",
      "God of War": "Combina acción con aventura",
      "Red Dead Redemption": "Deja moverse libremente por un mundo abierto",
      Pokémon: "Se trata de atrapar y entrenar criaturas",
      "Animal Crossing": "Simula la vida cotidiana",
      "League of Legends": "Se juega online, en equipo contra otro equipo",
      Valorant: "Se juega en línea, a los tiros, contra otros",
      "Counter-Strike": "Se juega en línea, a los tiros, contra otros",
      "Fall Guys": "Varios jugadores compiten esquivando obstáculos",
      Roblox: "Los propios jugadores crean contenido dentro del juego",
      Tetris: "El desafío pasa por resolver un rompecabezas",
      Sonic: "Hay que saltar entre plataformas para avanzar",
      "Street Fighter": "Enfrenta a dos personajes en combate",
      "Mortal Kombat": "Enfrenta a dos personajes en combate",
      "The Sims": "Simula la vida cotidiana",
      Overwatch: "Se juega online, en equipo contra otro equipo",
      Halo: "El objetivo pasa por disparar",
      "Resident Evil": "Mezcla terror con supervivencia",
      "Elden Ring": "Combina rol con aventura",
      "Genshin Impact": "Combina rol con un mundo abierto para explorar",
    },
    words: [
      "Minecraft",
      "Fortnite",
      "Among Us",
      "The Legend of Zelda",
      "Super Mario Bros",
      "Grand Theft Auto",
      "Call of Duty",
      "FIFA",
      "The Last of Us",
      "God of War",
      "Red Dead Redemption",
      "Pokémon",
      "Animal Crossing",
      "League of Legends",
      "Valorant",
      "Counter-Strike",
      "Fall Guys",
      "Roblox",
      "Tetris",
      "Sonic",
      "Street Fighter",
      "Mortal Kombat",
      "The Sims",
      "Overwatch",
      "Halo",
      "Resident Evil",
      "Elden Ring",
      "Genshin Impact",
    ],
  },
  peliculas: {
    label: "Películas Famosas",
    icon: "🎥",
    hints: {
      Titanic: "Es un drama con foco en una historia de amor",
      "El Padrino": "Es un drama centrado en el crimen organizado",
      "Star Wars": "Está ambientada en un contexto de ciencia ficción",
      "Jurassic Park": "Mezcla aventura con ciencia ficción",
      "El Señor de los Anillos": "Transcurre en un mundo de fantasía",
      "Harry Potter": "Transcurre en un mundo de fantasía",
      Avatar: "Está ambientada en un contexto de ciencia ficción",
      "Los Vengadores": "Está protagonizada por superhéroes",
      "El Rey León": "Está hecha con animación, no con actores",
      "Forrest Gump": "Es una historia con tono dramático",
      Matrix: "Combina ciencia ficción con acción",
      "Pulp Fiction": "Es un drama centrado en el mundo del crimen",
      "El Origen": "Está ambientada en un contexto de ciencia ficción",
      Interestelar: "Está ambientada en un contexto de ciencia ficción",
      Coco: "Está hecha con animación, no con actores",
      Frozen: "Está hecha con animación, no con actores",
      "Toy Story": "Está hecha con animación, no con actores",
      Shrek: "Está hecha con animación, no con actores",
      Joker: "Cuenta el origen de un villano de cómic",
      Parásitos: "Tiene tono dramático con algo de suspenso",
      "La La Land": "Tiene números musicales y una historia de amor",
      Gladiador: "Transcurre en un contexto histórico, con acción",
      Rocky: "Combina el deporte con el drama",
      "Volver al Futuro": "Mezcla ciencia ficción con comedia",
      Jaws: "Está pensada para tener en vilo al espectador",
      "E.T.": "Combina ciencia ficción con aventura",
      "Los Increíbles": "Está hecha con animación, no con actores",
    },
    words: [
      "Titanic",
      "El Padrino",
      "Star Wars",
      "Jurassic Park",
      "El Señor de los Anillos",
      "Harry Potter",
      "Avatar",
      "Los Vengadores",
      "El Rey León",
      "Forrest Gump",
      "Matrix",
      "Pulp Fiction",
      "El Origen",
      "Interestelar",
      "Coco",
      "Frozen",
      "Toy Story",
      "Shrek",
      "Joker",
      "Parásitos",
      "La La Land",
      "Gladiador",
      "Rocky",
      "Volver al Futuro",
      "Jaws",
      "E.T.",
      "Los Increíbles",
    ],
  },
  series: {
    label: "Series de TV",
    icon: "📺",
    hints: {
      Friends: "Apuesta todo a la comedia",
      "Breaking Bad": "Es un drama centrado en el mundo del crimen",
      "Game of Thrones": "Transcurre en un mundo de fantasía",
      "Stranger Things": "Mezcla ciencia ficción con misterio",
      "The Office": "Apuesta todo a la comedia",
      "La Casa de Papel": "Es un drama centrado en la planificación de un robo",
      "Los Simpson": "Está hecha con animación, no con actores",
      "Grey's Anatomy": "Transcurre en un ámbito hospitalario",
      "How I Met Your Mother": "Apuesta todo a la comedia",
      "The Walking Dead": "Mezcla terror con supervivencia",
      "Peaky Blinders": "Es un drama centrado en el mundo del crimen",
      Narcos: "Es un drama centrado en el mundo del crimen",
      "Black Mirror": "Está ambientada en un contexto de ciencia ficción",
      "The Crown": "Transcurre en un contexto histórico",
      "Better Call Saul": "Es un drama centrado en el mundo del crimen",
      Sherlock: "Gira en torno a resolver misterios",
      Dark: "Mezcla ciencia ficción con misterio",
      Élite: "Está centrada en personajes adolescentes o jóvenes",
      Vikingos: "Transcurre en un contexto histórico",
      "El Chavo del 8": "Apuesta todo a la comedia",
      "Rick and Morty": "Está hecha con animación, no con actores",
      "South Park": "Está hecha con animación, no con actores",
      "Bob Esponja": "Está hecha con animación, no con actores",
      Euphoria: "Está centrada en personajes adolescentes o jóvenes",
      Wednesday: "Mezcla protagonistas jóvenes con misterio",
    },
    words: [
      "Friends",
      "Breaking Bad",
      "Game of Thrones",
      "Stranger Things",
      "The Office",
      "La Casa de Papel",
      "Los Simpson",
      "Grey's Anatomy",
      "How I Met Your Mother",
      "The Walking Dead",
      "Peaky Blinders",
      "Narcos",
      "Black Mirror",
      "The Crown",
      "Better Call Saul",
      "Sherlock",
      "Dark",
      "Élite",
      "Vikingos",
      "El Chavo del 8",
      "Rick and Morty",
      "South Park",
      "Bob Esponja",
      "Euphoria",
      "Wednesday",
    ],
  },
  profesiones: {
    label: "Profesiones",
    icon: "💼",
    hints: {
      Médico: "Se dedica a cuidar la salud de las personas",
      Enfermero: "Se dedica a cuidar la salud de las personas",
      Bombero: "Actúa en situaciones de emergencia",
      Policía: "Se dedica a la seguridad de las personas",
      Abogado: "Exige varios años de estudio universitario",
      Maestro: "Se dedica a enseñarle a otras personas",
      Ingeniero: "Exige varios años de estudio universitario",
      Arquitecto: "Exige varios años de estudio universitario",
      Piloto: "Su trabajo tiene que ver con trasladar gente o cosas",
      Chef: "Se dedica a preparar comida",
      Peluquero: "Es un trabajo que se aprende más con la práctica que con estudios",
      Electricista: "Es un trabajo que se aprende más con la práctica que con estudios",
      Plomero: "Es un trabajo que se aprende más con la práctica que con estudios",
      Carpintero: "Es un trabajo que se aprende más con la práctica que con estudios",
      Veterinario: "Se dedica a cuidar la salud de las personas",
      Psicólogo: "Se dedica a cuidar la salud de las personas",
      Periodista: "Su trabajo es contar o difundir información",
      Fotógrafo: "Se desempeña en un rubro artístico o creativo",
      Actor: "Se desempeña en un rubro artístico o creativo",
      Músico: "Se desempeña en un rubro artístico o creativo",
      Programador: "Exige manejo técnico de tecnología",
      Contador: "Exige varios años de estudio universitario",
      Dentista: "Se dedica a cuidar la salud de las personas",
      Farmacéutico: "Se dedica a cuidar la salud de las personas",
      Albañil: "Es un trabajo que se aprende más con la práctica que con estudios",
      Panadero: "Se dedica a preparar comida",
      Mecánico: "Es un trabajo que se aprende más con la práctica que con estudios",
      Astronauta: "Necesita una preparación muy específica y poco común",
    },
    words: [
      "Médico",
      "Enfermero",
      "Bombero",
      "Policía",
      "Abogado",
      "Maestro",
      "Ingeniero",
      "Arquitecto",
      "Piloto",
      "Chef",
      "Peluquero",
      "Electricista",
      "Plomero",
      "Carpintero",
      "Veterinario",
      "Psicólogo",
      "Periodista",
      "Fotógrafo",
      "Actor",
      "Músico",
      "Programador",
      "Contador",
      "Dentista",
      "Farmacéutico",
      "Albañil",
      "Panadero",
      "Mecánico",
      "Astronauta",
    ],
  },
  marcas: {
    label: "Marcas Famosas",
    icon: "🏷️",
    hints: {
      "Coca-Cola": "Se dedica a producir bebidas",
      Pepsi: "Se dedica a producir bebidas",
      "McDonald's": "Es una cadena de comida rápida",
      Nike: "Fabrica ropa o calzado deportivo",
      Adidas: "Fabrica ropa o calzado deportivo",
      Apple: "Se dedica a la tecnología",
      Samsung: "Se dedica a la tecnología",
      Google: "Se dedica a la tecnología",
      Amazon: "Está ligada a la tecnología o al comercio online",
      Netflix: "Se dedica al entretenimiento",
      Disney: "Se dedica al entretenimiento",
      Ferrari: "Fabrica vehículos",
      Toyota: "Fabrica vehículos",
      BMW: "Fabrica vehículos",
      Starbucks: "Se dedica a producir bebidas",
      IKEA: "Se dedica a muebles o artículos para el hogar",
      Gucci: "Pertenece al mundo de la moda o el lujo",
      Chanel: "Pertenece al mundo de la moda o el lujo",
      Rolex: "Pertenece al mundo de la moda o el lujo",
      Lego: "Se dedica a juguetes o videojuegos",
      Sony: "Está ligada a la tecnología o el entretenimiento",
      Nintendo: "Se dedica a juguetes o videojuegos",
      PlayStation: "Se dedica a juguetes o videojuegos",
      Xbox: "Se dedica a juguetes o videojuegos",
      Instagram: "Está ligada a la tecnología o las redes sociales",
      WhatsApp: "Está ligada a la tecnología o las redes sociales",
      TikTok: "Está ligada a la tecnología o las redes sociales",
    },
    words: [
      "Coca-Cola",
      "Pepsi",
      "McDonald's",
      "Nike",
      "Adidas",
      "Apple",
      "Samsung",
      "Google",
      "Amazon",
      "Netflix",
      "Disney",
      "Ferrari",
      "Toyota",
      "BMW",
      "Starbucks",
      "IKEA",
      "Gucci",
      "Chanel",
      "Rolex",
      "Lego",
      "Sony",
      "Nintendo",
      "PlayStation",
      "Xbox",
      "Instagram",
      "WhatsApp",
      "TikTok",
    ],
  },
  lugares: {
    label: "Lugares Turísticos",
    icon: "🗺️",
    hints: {
      "Torre Eiffel": "Fue construido por el hombre, en Europa",
      "Coliseo Romano": "Es una construcción muy antigua",
      "Machu Picchu": "Es una construcción antigua ubicada en Sudamérica",
      "Gran Muralla China": "Es una construcción muy antigua",
      "Taj Mahal": "Fue construido por el hombre, en Asia",
      "Cataratas del Iguazú": "Es un paisaje natural ubicado en Sudamérica",
      "Estatua de la Libertad": "Fue construido por el hombre, en América",
      "Torre de Pisa": "Fue construido por el hombre, en Europa",
      "Sagrada Familia": "Tiene un fin religioso y está en Europa",
      "Big Ben": "Fue construido por el hombre, en Europa",
      "Cristo Redentor": "Tiene un fin religioso y está en Sudamérica",
      "Pirámides de Egipto": "Es una construcción muy antigua",
      "Times Square": "Es un punto urbano y moderno de América",
      "Las Vegas": "Es un punto urbano y moderno de América",
      Disneyland: "Es un lugar moderno pensado para el entretenimiento",
      "Chichén Itzá": "Es una construcción antigua ubicada en América",
      "Salar de Uyuni": "Es un paisaje natural ubicado en Sudamérica",
      "Islas Galápagos": "Es un paisaje natural ubicado en Sudamérica",
      "Gran Cañón": "Es un paisaje natural ubicado en Norteamérica",
      "Muralla de Berlín": "Es una construcción moderna ubicada en Europa",
      Kremlin: "Fue construido por el hombre, en Europa",
      "Ópera de Sídney": "Es una construcción moderna ubicada en Oceanía",
      "Monte Everest": "Es un paisaje natural ubicado en Asia",
      Amazonas: "Es un paisaje natural ubicado en Sudamérica",
    },
    words: [
      "Torre Eiffel",
      "Coliseo Romano",
      "Machu Picchu",
      "Gran Muralla China",
      "Taj Mahal",
      "Cataratas del Iguazú",
      "Estatua de la Libertad",
      "Torre de Pisa",
      "Sagrada Familia",
      "Big Ben",
      "Cristo Redentor",
      "Pirámides de Egipto",
      "Times Square",
      "Las Vegas",
      "Disneyland",
      "Chichén Itzá",
      "Salar de Uyuni",
      "Islas Galápagos",
      "Gran Cañón",
      "Muralla de Berlín",
      "Kremlin",
      "Ópera de Sídney",
      "Monte Everest",
      "Amazonas",
    ],
  },
};
