// ─── Game Data ───────────────────────────────────────────────────────────────
export interface Category {
  label: string;
  icon: string;
  words: string[];
  // Per-word hint shown only to the impostor (if the host enables hints) —
  // a deliberately vague clue that fits many entries in the category, so it
  // helps them bluff a little without giving away which word it actually is.
  hints: Record<string, string>;
}

export const CATEGORIES: Record<string, Category> = {
  futbolistas: {
    label: "Jugadores de Fútbol",
    icon: "⚽",
    hints: {
      "Messi": "Jugó principalmente como delantero o extremo",
      "Cristiano Ronaldo": "Jugó principalmente como delantero o extremo",
      "Neymar": "Jugó principalmente como delantero o extremo",
      "Mbappé": "Juega principalmente como delantero o extremo",
      "Haaland": "Juega principalmente como delantero",
      "Benzema": "Jugó principalmente como delantero",
      "Lewandowski": "Juega principalmente como delantero",
      "Salah": "Juega principalmente como delantero o extremo",
      "De Bruyne": "Juega principalmente en el mediocampo",
      "Modric": "Juega principalmente en el mediocampo",
      "Vinicius Jr": "Juega principalmente como delantero o extremo",
      "Pedri": "Juega principalmente en el mediocampo",
      "Gavi": "Juega principalmente en el mediocampo",
      "Bellingham": "Juega principalmente en el mediocampo",
      "Lautaro Martínez": "Juega principalmente como delantero",
      "Álvarez": "Juega principalmente como delantero",
      "Dybala": "Juega principalmente como delantero o extremo",
      "Di María": "Juega principalmente como extremo o mediocampista",
      "Rooney": "Jugó principalmente como delantero",
      "Gerrard": "Jugó principalmente en el mediocampo",
      "Lampard": "Jugó principalmente en el mediocampo",
      "Beckham": "Jugó principalmente en el mediocampo",
      "Henry": "Jugó principalmente como delantero",
      "Zidane": "Jugó principalmente en el mediocampo",
      "Ronaldinho": "Jugó principalmente como delantero o extremo",
      "Maradona": "Jugó principalmente como delantero o mediocampista",
      "Pelé": "Jugó principalmente como delantero",
      "Buffon": "Jugó como arquero",
      "Casillas": "Jugó como arquero",
      "Neuer": "Juega como arquero",
      "Ter Stegen": "Juega como arquero",
      "De Gea": "Juega como arquero",
      "Oblak": "Juega como arquero",
      "Courtois": "Juega como arquero",
      "Alisson": "Juega como arquero",
      "Ramos": "Jugó principalmente como defensor",
      "Piqué": "Jugó principalmente como defensor",
      "Varane": "Juega principalmente como defensor",
      "Trent Alexander-Arnold": "Juega principalmente como defensor",
      "Marcelo": "Jugó principalmente como defensor",
      "Griezmann": "Juega principalmente como delantero",
      "Suárez": "Jugó principalmente como delantero",
      "Cavani": "Jugó principalmente como delantero",
      "Agüero": "Jugó principalmente como delantero",
      "Higuaín": "Jugó principalmente como delantero",
      "Tevez": "Jugó principalmente como delantero",
      "Riquelme": "Jugó principalmente en el mediocampo",
      "Verón": "Jugó principalmente en el mediocampo",
      "Kaká": "Jugó principalmente en el mediocampo",
      "Iniesta": "Jugó principalmente en el mediocampo",
      "Xavi": "Jugó principalmente en el mediocampo",
      "Puyol": "Jugó principalmente como defensor",
      "Van Dijk": "Juega principalmente como defensor",
      "Kanté": "Juega principalmente en el mediocampo",
      "Pogba": "Juega principalmente en el mediocampo",
    },
    words: [
      "Messi",
      "Cristiano Ronaldo",
      "Neymar",
      "Mbappé",
      "Haaland",
      "Benzema",
      "Lewandowski",
      "Salah",
      "De Bruyne",
      "Modric",
      "Vinicius Jr",
      "Pedri",
      "Gavi",
      "Bellingham",
      "Lautaro Martínez",
      "Álvarez",
      "Dybala",
      "Di María",
      "Rooney",
      "Gerrard",
      "Lampard",
      "Beckham",
      "Henry",
      "Zidane",
      "Ronaldinho",
      "Maradona",
      "Pelé",
      "Buffon",
      "Casillas",
      "Neuer",
      "Ter Stegen",
      "De Gea",
      "Oblak",
      "Courtois",
      "Alisson",
      "Ramos",
      "Piqué",
      "Varane",
      "Trent Alexander-Arnold",
      "Marcelo",
      "Griezmann",
      "Suárez",
      "Cavani",
      "Agüero",
      "Higuaín",
      "Tevez",
      "Riquelme",
      "Verón",
      "Kaká",
      "Iniesta",
      "Xavi",
      "Puyol",
      "Van Dijk",
      "Kanté",
      "Pogba",
    ],
  },
  selecciones: {
    label: "Selecciones de Fútbol",
    icon: "🏆",
    hints: {
      "Argentina": "Es un país sudamericano",
      "Brasil": "Es un país sudamericano",
      "Francia": "Es un país europeo",
      "Alemania": "Es un país europeo",
      "España": "Es un país europeo",
      "Portugal": "Es un país europeo",
      "Italia": "Es un país europeo",
      "Inglaterra": "Es un país de habla predominantemente inglesa",
      "Países Bajos": "Es un país europeo",
      "Bélgica": "Es un país europeo",
      "Uruguay": "Es un país sudamericano",
      "Colombia": "Es un país sudamericano",
      "México": "Es un país de América del Norte o Central",
      "Japón": "Es un país asiático",
      "Senegal": "Es un país africano",
      "Marruecos": "Es un país africano",
      "Ghana": "Es un país africano",
      "Ecuador": "Es un país sudamericano",
      "Perú": "Es un país sudamericano",
      "Chile": "Es un país sudamericano",
      "Paraguay": "Es un país sudamericano",
      "Australia": "Es un país de habla predominantemente inglesa",
      "Croacia": "Es un país europeo",
      "Suiza": "Es un país europeo",
      "Dinamarca": "Es un país europeo",
      "Polonia": "Es un país europeo",
      "Suecia": "Es un país europeo",
      "Serbia": "Es un país europeo",
      "Turquía": "Es un país euroasiático",
      "Ucrania": "Es un país europeo",
      "Costa Rica": "Es un país de América del Norte o Central",
      "Panamá": "Es un país de América del Norte o Central",
      "Venezuela": "Es un país sudamericano",
      "Túnez": "Es un país africano",
      "Argelia": "Es un país africano",
      "Camerún": "Es un país africano",
      "Nigeria": "Es un país africano",
      "Irán": "Es un país asiático",
      "Arabia Saudita": "Es un país asiático",
      "Catar": "Es un país asiático",
      "Corea del Sur": "Es un país asiático",
      "Estados Unidos": "Es un país de habla predominantemente inglesa",
      "Canadá": "Es un país de habla predominantemente inglesa",
      "Gales": "Es un país de habla predominantemente inglesa",
      "Escocia": "Es un país de habla predominantemente inglesa",
    },
    words: [
      "Argentina",
      "Brasil",
      "Francia",
      "Alemania",
      "España",
      "Portugal",
      "Italia",
      "Inglaterra",
      "Países Bajos",
      "Bélgica",
      "Uruguay",
      "Colombia",
      "México",
      "Japón",
      "Senegal",
      "Marruecos",
      "Ghana",
      "Ecuador",
      "Perú",
      "Chile",
      "Paraguay",
      "Australia",
      "Croacia",
      "Suiza",
      "Dinamarca",
      "Polonia",
      "Suecia",
      "Serbia",
      "Turquía",
      "Ucrania",
      "Costa Rica",
      "Panamá",
      "Venezuela",
      "Túnez",
      "Argelia",
      "Camerún",
      "Nigeria",
      "Irán",
      "Arabia Saudita",
      "Catar",
      "Corea del Sur",
      "Estados Unidos",
      "Canadá",
      "Gales",
      "Escocia",
    ],
  },
  actores: {
    label: "Actores Famosos",
    icon: "🎬",
    hints: {
      "Tom Hanks": "Es un actor reconocido por papeles dramáticos",
      "Brad Pitt": "Es un actor reconocido por papeles de acción y drama",
      "Leonardo DiCaprio": "Es un actor reconocido por papeles dramáticos",
      "Angelina Jolie": "Es una actriz reconocida por papeles de acción y drama",
      "Meryl Streep": "Es una actriz reconocida por papeles dramáticos",
      "Scarlett Johansson": "Es una actriz que también participó en películas de superhéroes",
      "Robert Downey Jr": "Es un actor que también participó en películas de superhéroes",
      "Johnny Depp": "Es un actor reconocido por papeles excéntricos",
      "Will Smith": "Es un actor que también incursionó en la música",
      "Denzel Washington": "Es un actor reconocido por papeles dramáticos",
      "Morgan Freeman": "Es un actor reconocido por su voz y papeles dramáticos",
      "Anthony Hopkins": "Es un actor reconocido por papeles dramáticos",
      "Cate Blanchett": "Es una actriz reconocida por papeles dramáticos",
      "Natalie Portman": "Es una actriz que también participó en películas de fantasía o ciencia ficción",
      "Julia Roberts": "Es una actriz reconocida por comedias románticas",
      "Jennifer Aniston": "Es una actriz reconocida por comedias",
      "Sandra Bullock": "Es una actriz reconocida por comedias y dramas",
      "Nicole Kidman": "Es una actriz reconocida por papeles dramáticos",
      "Ryan Reynolds": "Es un actor que también participó en películas de superhéroes",
      "Ryan Gosling": "Es un actor reconocido por dramas y comedias románticas",
      "Chris Evans": "Es un actor que también participó en películas de superhéroes",
      "Chris Hemsworth": "Es un actor que también participó en películas de superhéroes",
      "Dwayne Johnson": "Es un actor que también fue deportista antes de actuar",
      "Keanu Reeves": "Es un actor reconocido por películas de acción",
      "Joaquin Phoenix": "Es un actor reconocido por papeles dramáticos",
      "Tom Cruise": "Es un actor reconocido por películas de acción",
      "Harrison Ford": "Es un actor reconocido por películas de acción y aventura",
      "Al Pacino": "Es un actor reconocido por papeles dramáticos",
      "Robert De Niro": "Es un actor reconocido por papeles dramáticos",
      "Jack Nicholson": "Es un actor reconocido por papeles dramáticos",
      "Penélope Cruz": "Es una actriz reconocida por papeles dramáticos",
      "Antonio Banderas": "Es un actor que también incursionó en el cine animado como voz",
      "Salma Hayek": "Es una actriz reconocida por dramas y comedias",
      "Emma Watson": "Es una actriz que se hizo conocida siendo niña o adolescente",
      "Emma Stone": "Es una actriz reconocida por comedias y dramas",
      "Margot Robbie": "Es una actriz que también participó en películas de superhéroes",
      "Zendaya": "Es una actriz que se hizo conocida siendo niña o adolescente",
      "Timothée Chalamet": "Es un actor joven reconocido por papeles dramáticos",
      "Tom Holland": "Es un actor que también participó en películas de superhéroes",
      "Robert Pattinson": "Es un actor que también participó en películas de superhéroes",
      "Jason Momoa": "Es un actor que también participó en películas de superhéroes",
      "Gal Gadot": "Es una actriz que también participó en películas de superhéroes",
      "Charlize Theron": "Es una actriz reconocida por papeles de acción y drama",
      "Hugh Jackman": "Es un actor que también participó en películas de superhéroes",
      "Samuel L. Jackson": "Es un actor que también participó en películas de superhéroes",
      "Matthew McConaughey": "Es un actor reconocido por dramas y comedias románticas",
      "Christian Bale": "Es un actor que también participó en películas de superhéroes",
    },
    words: [
      "Tom Hanks",
      "Brad Pitt",
      "Leonardo DiCaprio",
      "Angelina Jolie",
      "Meryl Streep",
      "Scarlett Johansson",
      "Robert Downey Jr",
      "Johnny Depp",
      "Will Smith",
      "Denzel Washington",
      "Morgan Freeman",
      "Anthony Hopkins",
      "Cate Blanchett",
      "Natalie Portman",
      "Julia Roberts",
      "Jennifer Aniston",
      "Sandra Bullock",
      "Nicole Kidman",
      "Ryan Reynolds",
      "Ryan Gosling",
      "Chris Evans",
      "Chris Hemsworth",
      "Dwayne Johnson",
      "Keanu Reeves",
      "Joaquin Phoenix",
      "Tom Cruise",
      "Harrison Ford",
      "Al Pacino",
      "Robert De Niro",
      "Jack Nicholson",
      "Penélope Cruz",
      "Antonio Banderas",
      "Salma Hayek",
      "Emma Watson",
      "Emma Stone",
      "Margot Robbie",
      "Zendaya",
      "Timothée Chalamet",
      "Tom Holland",
      "Robert Pattinson",
      "Jason Momoa",
      "Gal Gadot",
      "Charlize Theron",
      "Hugh Jackman",
      "Samuel L. Jackson",
      "Matthew McConaughey",
      "Christian Bale",
    ],
  },
  historicos: {
    label: "Personajes Históricos",
    icon: "📜",
    hints: {
      "Napoleón Bonaparte": "Fue una figura política o militar",
      "Julio César": "Vivió en la antigüedad",
      "Alejandro Magno": "Vivió en la antigüedad",
      "Cleopatra": "Vivió en la antigüedad",
      "Leonardo Da Vinci": "Fue una figura del arte o el pensamiento",
      "Albert Einstein": "Fue una figura de la ciencia",
      "Isaac Newton": "Fue una figura de la ciencia",
      "Galileo Galilei": "Fue una figura de la ciencia",
      "Charles Darwin": "Fue una figura de la ciencia",
      "Nikola Tesla": "Fue una figura de la ciencia o la tecnología",
      "Marie Curie": "Fue una figura de la ciencia",
      "Abraham Lincoln": "Fue una figura política o de gobierno",
      "Winston Churchill": "Fue una figura política o de gobierno",
      "Genghis Khan": "Vivió en la época medieval",
      "Marco Polo": "Vivió en la época medieval",
      "Cristóbal Colón": "Vivió en la época medieval",
      "Martin Luther King": "Fue una figura política o de derechos civiles",
      "Nelson Mandela": "Fue una figura política o de derechos civiles",
      "Gandhi": "Fue una figura política o de derechos civiles",
      "Simon Bolívar": "Fue una figura política o militar",
      "San Martín": "Fue una figura política o militar",
      "Fidel Castro": "Fue una figura política o de gobierno",
      "Che Guevara": "Fue una figura política o militar",
      "Mozart": "Fue una figura del arte o el pensamiento",
      "Beethoven": "Fue una figura del arte o el pensamiento",
      "Shakespeare": "Fue una figura del arte o el pensamiento",
      "Cervantes": "Fue una figura del arte o el pensamiento",
      "Aristóteles": "Vivió en la antigüedad",
      "Platón": "Vivió en la antigüedad",
      "Sócrates": "Vivió en la antigüedad",
      "Confucio": "Vivió en la antigüedad",
      "Buda": "Vivió en la antigüedad",
      "Juana de Arco": "Vivió en la época medieval",
      "Isaac Asimov": "Fue una figura de la ciencia o la literatura",
      "Stephen Hawking": "Fue una figura de la ciencia",
      "Thomas Edison": "Fue una figura de la ciencia o la tecnología",
      "Henry Ford": "Fue una figura de la industria o la tecnología",
      "Steve Jobs": "Fue una figura de la tecnología",
      "Bill Gates": "Fue una figura de la tecnología",
      "Rosa Parks": "Fue una figura política o de derechos civiles",
      "Anne Frank": "Vivió en el siglo XX",
      "Eva Perón": "Fue una figura política",
    },
    words: [
      "Napoleón Bonaparte",
      "Julio César",
      "Alejandro Magno",
      "Cleopatra",
      "Leonardo Da Vinci",
      "Albert Einstein",
      "Isaac Newton",
      "Galileo Galilei",
      "Charles Darwin",
      "Nikola Tesla",
      "Marie Curie",
      "Abraham Lincoln",
      "Winston Churchill",
      "Genghis Khan",
      "Marco Polo",
      "Cristóbal Colón",
      "Martin Luther King",
      "Nelson Mandela",
      "Gandhi",
      "Simon Bolívar",
      "San Martín",
      "Fidel Castro",
      "Che Guevara",
      "Mozart",
      "Beethoven",
      "Shakespeare",
      "Cervantes",
      "Aristóteles",
      "Platón",
      "Sócrates",
      "Confucio",
      "Buda",
      "Juana de Arco",
      "Isaac Asimov",
      "Stephen Hawking",
      "Thomas Edison",
      "Henry Ford",
      "Steve Jobs",
      "Bill Gates",
      "Rosa Parks",
      "Anne Frank",
      "Eva Perón",
    ],
  },
  objetos: {
    label: "Objetos Cotidianos",
    icon: "🪑",
    hints: {
      "Silla": "Es un mueble",
      "Mesa": "Es un mueble",
      "Televisor": "Funciona con electricidad",
      "Teléfono": "Funciona con electricidad",
      "Computadora": "Funciona con electricidad",
      "Refrigerador": "Se usa en la cocina",
      "Lavadora": "Funciona con electricidad",
      "Microondas": "Se usa en la cocina",
      "Cama": "Es un mueble",
      "Almohada": "Se usa para descansar",
      "Espejo": "Se suele tener en una habitación",
      "Reloj": "Se usa para saber la hora",
      "Lámpara": "Funciona con electricidad",
      "Ventilador": "Funciona con electricidad",
      "Aspiradora": "Funciona con electricidad",
      "Cafetera": "Se usa en la cocina",
      "Tostadora": "Se usa en la cocina",
      "Licuadora": "Se usa en la cocina",
      "Plancha": "Funciona con electricidad",
      "Tijeras": "Es una herramienta cortante",
      "Martillo": "Es una herramienta",
      "Destornillador": "Es una herramienta",
      "Paraguas": "No se usa todos los días",
      "Mochila": "Se usa para llevar cosas",
      "Maleta": "Se usa para llevar cosas",
      "Billetera": "Se lleva encima al salir de casa",
      "Bolígrafo": "Se usa para escribir",
      "Cuaderno": "Se usa para escribir",
      "Zapatos": "Se usa al salir de casa",
      "Gafas de sol": "Se usa al salir de casa",
      "Taza": "Se usa en la cocina",
      "Vaso": "Se usa en la cocina",
      "Plato": "Se usa en la cocina",
      "Olla": "Se usa en la cocina",
      "Sartén": "Se usa en la cocina",
      "Cuchillo": "Se usa en la cocina",
      "Tabla de cortar": "Se usa en la cocina",
      "Control remoto": "Funciona con pilas o electricidad",
      "Cargador de celular": "Funciona con electricidad",
      "Auriculares": "Funciona con electricidad",
      "Escoba": "Se usa para la limpieza del hogar",
      "Balde": "Se usa para la limpieza del hogar",
      "Toalla": "Se usa para el aseo personal",
      "Almohadón": "Se suele tener en una habitación",
      "Frazada": "Se usa para descansar",
      "Colgador de ropa": "Se usa para el hogar",
      "Linterna": "No se usa todos los días",
      "Vela": "No se usa todos los días",
      "Fósforos": "No se usa todos los días",
      "Candado": "No se usa todos los días",
      "Llavero": "Se lleva encima al salir de casa",
    },
    words: [
      "Silla",
      "Mesa",
      "Televisor",
      "Teléfono",
      "Computadora",
      "Refrigerador",
      "Lavadora",
      "Microondas",
      "Cama",
      "Almohada",
      "Espejo",
      "Reloj",
      "Lámpara",
      "Ventilador",
      "Aspiradora",
      "Cafetera",
      "Tostadora",
      "Licuadora",
      "Plancha",
      "Tijeras",
      "Martillo",
      "Destornillador",
      "Paraguas",
      "Mochila",
      "Maleta",
      "Billetera",
      "Bolígrafo",
      "Cuaderno",
      "Zapatos",
      "Gafas de sol",
      "Taza",
      "Vaso",
      "Plato",
      "Olla",
      "Sartén",
      "Cuchillo",
      "Tabla de cortar",
      "Control remoto",
      "Cargador de celular",
      "Auriculares",
      "Escoba",
      "Balde",
      "Toalla",
      "Almohadón",
      "Frazada",
      "Colgador de ropa",
      "Linterna",
      "Vela",
      "Fósforos",
      "Candado",
      "Llavero",
    ],
  },
  animales: {
    label: "Animales",
    icon: "🦁",
    hints: {
      "León": "Es un mamífero terrestre de gran tamaño",
      "Tigre": "Es un mamífero terrestre de gran tamaño",
      "Elefante": "Es un mamífero terrestre de gran tamaño",
      "Jirafa": "Es un mamífero terrestre de gran tamaño",
      "Hipopótamo": "Es un mamífero terrestre de gran tamaño",
      "Rinoceronte": "Es un mamífero terrestre de gran tamaño",
      "Cebra": "Es un mamífero terrestre de gran tamaño",
      "Gorila": "Es un mamífero terrestre de gran tamaño",
      "Delfín": "Vive en el agua",
      "Ballena": "Vive en el agua y es de gran tamaño",
      "Tiburón": "Vive en el agua",
      "Pulpo": "Vive en el agua",
      "Tortuga marina": "Vive en el agua",
      "Águila": "Puede volar",
      "Pingüino": "Es un ave, aunque no puede volar",
      "Flamenco": "Es un ave",
      "Pavo real": "Es un ave",
      "Colibrí": "Puede volar y es pequeño",
      "Búho": "Puede volar",
      "Perro": "Es una mascota común",
      "Gato": "Es una mascota común",
      "Conejo": "Es un mamífero pequeño",
      "Panda": "Es un mamífero de gran tamaño",
      "Koala": "Es un mamífero de tamaño mediano",
      "Canguro": "Es un mamífero de tamaño mediano",
      "Ornitorrinco": "Es un mamífero poco común",
      "Anaconda": "Es un reptil sin patas",
      "Cobra": "Es un reptil sin patas",
      "Camaleón": "Es un reptil",
      "Caballo": "Es un mamífero de granja o campo",
      "Vaca": "Es un mamífero de granja",
      "Cerdo": "Es un mamífero de granja",
      "Oveja": "Es un mamífero de granja",
      "Camello": "Es un mamífero de gran tamaño",
      "Axolotl": "Vive en el agua",
      "Lobo": "Es un mamífero carnívoro salvaje",
      "Zorro": "Es un mamífero carnívoro salvaje",
      "Oso": "Es un mamífero de gran tamaño",
      "Oso polar": "Es un mamífero de gran tamaño",
      "Mapache": "Es un mamífero pequeño y salvaje",
      "Ardilla": "Es un mamífero pequeño",
      "Erizo": "Es un mamífero pequeño",
      "Murciélago": "Puede volar",
      "Rana": "Vive dentro y fuera del agua",
      "Sapo": "Vive dentro y fuera del agua",
      "Lagarto": "Es un reptil",
      "Cocodrilo": "Vive dentro y fuera del agua",
      "Buitre": "Puede volar",
      "Cisne": "Es un ave que vive en el agua",
      "Pato": "Es un ave que vive en el agua",
      "Loro": "Puede volar",
      "Hormiga": "Es un insecto pequeño",
      "Abeja": "Es un insecto que puede volar",
      "Mariposa": "Es un insecto que puede volar",
      "Araña": "Es un invertebrado con muchas patas",
      "Escorpión": "Es un invertebrado con muchas patas",
      "Medusa": "Vive en el agua",
      "Estrella de mar": "Vive en el agua",
      "Cangrejo": "Vive en el agua o cerca de ella",
      "Langosta": "Vive en el agua",
    },
    words: [
      "León",
      "Tigre",
      "Elefante",
      "Jirafa",
      "Hipopótamo",
      "Rinoceronte",
      "Cebra",
      "Gorila",
      "Delfín",
      "Ballena",
      "Tiburón",
      "Pulpo",
      "Tortuga marina",
      "Águila",
      "Pingüino",
      "Flamenco",
      "Pavo real",
      "Colibrí",
      "Búho",
      "Perro",
      "Gato",
      "Conejo",
      "Panda",
      "Koala",
      "Canguro",
      "Ornitorrinco",
      "Anaconda",
      "Cobra",
      "Camaleón",
      "Caballo",
      "Vaca",
      "Cerdo",
      "Oveja",
      "Camello",
      "Axolotl",
      "Lobo",
      "Zorro",
      "Oso",
      "Oso polar",
      "Mapache",
      "Ardilla",
      "Erizo",
      "Murciélago",
      "Rana",
      "Sapo",
      "Lagarto",
      "Cocodrilo",
      "Buitre",
      "Cisne",
      "Pato",
      "Loro",
      "Hormiga",
      "Abeja",
      "Mariposa",
      "Araña",
      "Escorpión",
      "Medusa",
      "Estrella de mar",
      "Cangrejo",
      "Langosta",
    ],
  },
  paises: {
    label: "Países del Mundo",
    icon: "🌍",
    hints: {
      "China": "Es un país asiático",
      "India": "Es un país asiático",
      "Estados Unidos": "Es un país de América del Norte",
      "Indonesia": "Es un país asiático",
      "Brasil": "Es un país sudamericano",
      "Nigeria": "Es un país africano",
      "Japón": "Es un país asiático",
      "Egipto": "Es un país africano",
      "Alemania": "Es un país europeo",
      "Francia": "Es un país europeo",
      "Reino Unido": "Es un país europeo",
      "España": "Es un país europeo",
      "Italia": "Es un país europeo",
      "Argentina": "Es un país sudamericano",
      "Colombia": "Es un país sudamericano",
      "Canadá": "Es un país de América del Norte",
      "Australia": "Es un país de Oceanía",
      "Corea del Sur": "Es un país asiático",
      "Arabia Saudita": "Es un país asiático",
      "Sudáfrica": "Es un país africano",
      "Marruecos": "Es un país africano",
      "Suecia": "Es un país europeo",
      "Noruega": "Es un país europeo",
      "Dinamarca": "Es un país europeo",
      "Finlandia": "Es un país europeo",
      "Suiza": "Es un país europeo",
      "Austria": "Es un país europeo",
      "Bélgica": "Es un país europeo",
      "Polonia": "Es un país europeo",
      "Perú": "Es un país sudamericano",
      "Chile": "Es un país sudamericano",
      "Ecuador": "Es un país sudamericano",
      "Bolivia": "Es un país sudamericano",
      "Cuba": "Es un país de América Central o el Caribe",
      "Jamaica": "Es un país de América Central o el Caribe",
      "Portugal": "Es un país europeo",
      "Grecia": "Es un país europeo",
      "Turquía": "Es un país euroasiático",
      "Rusia": "Es un país euroasiático",
      "Ucrania": "Es un país europeo",
      "Nueva Zelanda": "Es un país de Oceanía",
      "Tailandia": "Es un país asiático",
      "Vietnam": "Es un país asiático",
      "Filipinas": "Es un país asiático",
      "Malasia": "Es un país asiático",
      "Singapur": "Es un país asiático",
      "Kenia": "Es un país africano",
      "Etiopía": "Es un país africano",
      "Islandia": "Es un país europeo",
      "Irlanda": "Es un país europeo",
      "Croacia": "Es un país europeo",
    },
    words: [
      "China",
      "India",
      "Estados Unidos",
      "Indonesia",
      "Brasil",
      "Nigeria",
      "Japón",
      "Egipto",
      "Alemania",
      "Francia",
      "Reino Unido",
      "España",
      "Italia",
      "Argentina",
      "Colombia",
      "Canadá",
      "Australia",
      "Corea del Sur",
      "Arabia Saudita",
      "Sudáfrica",
      "Marruecos",
      "Suecia",
      "Noruega",
      "Dinamarca",
      "Finlandia",
      "Suiza",
      "Austria",
      "Bélgica",
      "Polonia",
      "Perú",
      "Chile",
      "Ecuador",
      "Bolivia",
      "Cuba",
      "Jamaica",
      "Portugal",
      "Grecia",
      "Turquía",
      "Rusia",
      "Ucrania",
      "Nueva Zelanda",
      "Tailandia",
      "Vietnam",
      "Filipinas",
      "Malasia",
      "Singapur",
      "Kenia",
      "Etiopía",
      "Islandia",
      "Irlanda",
      "Croacia",
    ],
  },
  comidas: {
    label: "Comidas del Mundo",
    icon: "🍕",
    hints: {
      "Pizza": "Es un plato salado de origen europeo",
      "Sushi": "Es un plato de origen asiático",
      "Tacos": "Es un plato salado de origen latinoamericano",
      "Ramen": "Es un plato de origen asiático",
      "Paella": "Es un plato salado de origen europeo",
      "Spaghetti": "Es un plato salado de origen europeo",
      "Hamburguesa": "Es un plato salado que se come con las manos",
      "Asado": "Es un plato salado de origen latinoamericano",
      "Empanadas": "Es un plato salado de origen latinoamericano",
      "Ceviche": "Es un plato salado de origen latinoamericano",
      "Arepas": "Es un plato salado de origen latinoamericano",
      "Tamales": "Es un plato salado de origen latinoamericano",
      "Enchiladas": "Es un plato salado de origen latinoamericano",
      "Churros": "Es un postre dulce",
      "Croissant": "Es de origen europeo",
      "Fondue": "Es un plato de origen europeo",
      "Gyros": "Es un plato salado de origen mediterráneo",
      "Falafel": "Es un plato salado de origen mediterráneo",
      "Hummus": "Es un plato salado de origen mediterráneo",
      "Shawarma": "Es un plato salado de origen mediterráneo",
      "Curry": "Es un plato salado de origen asiático",
      "Pad Thai": "Es un plato de origen asiático",
      "Pho": "Es un plato de origen asiático",
      "Bibimbap": "Es un plato de origen asiático",
      "Kimchi": "Es un plato de origen asiático",
      "Dim Sum": "Es un plato de origen asiático",
      "Mole": "Es un plato salado de origen latinoamericano",
      "Locro": "Es un plato salado de origen latinoamericano",
      "Carbonada": "Es un plato salado de origen latinoamericano",
      "Milanesa": "Es un plato salado de origen latinoamericano",
      "Choripán": "Es un plato salado que se come con las manos",
      "Alfajores": "Es un postre dulce de origen latinoamericano",
      "Feijoada": "Es un plato salado de origen latinoamericano",
      "Brigadeiro": "Es un postre dulce de origen latinoamericano",
      "Dulce de leche": "Es un dulce de origen latinoamericano",
      "Milkshake": "Es una bebida o postre dulce y frío",
      "Helado": "Es un postre dulce y frío",
      "Panqueques": "Es un postre dulce",
      "Waffles": "Es un postre dulce",
      "Bruschetta": "Es un plato salado de origen europeo",
      "Lasaña": "Es un plato salado de origen europeo",
      "Risotto": "Es un plato salado de origen europeo",
      "Gnocchi": "Es un plato salado de origen europeo",
      "Kebab": "Es un plato salado de origen mediterráneo",
      "Baklava": "Es un postre dulce de origen mediterráneo",
      "Goulash": "Es un plato salado de origen europeo",
      "Fish and chips": "Es un plato salado de origen europeo",
      "Poutine": "Es un plato salado que se come con las manos o con tenedor",
      "Nachos": "Es un plato salado de origen latinoamericano",
      "Guacamole": "Es un plato salado de origen latinoamericano",
      "Quesadilla": "Es un plato salado de origen latinoamericano",
    },
    words: [
      "Pizza",
      "Sushi",
      "Tacos",
      "Ramen",
      "Paella",
      "Spaghetti",
      "Hamburguesa",
      "Asado",
      "Empanadas",
      "Ceviche",
      "Arepas",
      "Tamales",
      "Enchiladas",
      "Churros",
      "Croissant",
      "Fondue",
      "Gyros",
      "Falafel",
      "Hummus",
      "Shawarma",
      "Curry",
      "Pad Thai",
      "Pho",
      "Bibimbap",
      "Kimchi",
      "Dim Sum",
      "Mole",
      "Locro",
      "Carbonada",
      "Milanesa",
      "Choripán",
      "Alfajores",
      "Feijoada",
      "Brigadeiro",
      "Dulce de leche",
      "Milkshake",
      "Helado",
      "Panqueques",
      "Waffles",
      "Bruschetta",
      "Lasaña",
      "Risotto",
      "Gnocchi",
      "Kebab",
      "Baklava",
      "Goulash",
      "Fish and chips",
      "Poutine",
      "Nachos",
      "Guacamole",
      "Quesadilla",
    ],
  },
  deportes: {
    label: "Deportes",
    icon: "🏅",
    hints: {
      "Fútbol": "Se juega con pelota y en equipo",
      "Basketball": "Se juega con pelota y en equipo",
      "Tenis": "Se juega con pelota o raqueta, individual o en parejas",
      "Natación": "Se practica en el agua",
      "Atletismo": "Se practica de forma individual",
      "Boxeo": "Es un deporte de combate",
      "Ciclismo": "Se practica con un vehículo o rodado",
      "Golf": "Se juega con pelota en espacios abiertos",
      "Rugby": "Se juega con pelota y en equipo",
      "Béisbol": "Se juega con pelota y en equipo",
      "Volleyball": "Se juega con pelota y en equipo",
      "Handball": "Se juega con pelota y en equipo",
      "Hockey sobre hielo": "Se juega sobre hielo",
      "Esquí": "Se practica sobre nieve",
      "Snowboard": "Se practica sobre nieve",
      "Surf": "Se practica en el agua",
      "Escalada": "Se practica de forma individual",
      "Triatlón": "Combina varias disciplinas",
      "Esgrima": "Es un deporte de combate",
      "Judo": "Es un deporte de combate",
      "Karate": "Es un deporte de combate",
      "Taekwondo": "Es un deporte de combate",
      "Lucha libre": "Es un deporte de combate",
      "Halterofilia": "Se practica de forma individual",
      "Gimnasia artística": "Se practica de forma individual",
      "Patinaje artístico": "Se practica sobre hielo",
      "Polo": "Se juega con pelota usando un vehículo o animal",
      "Tiro con arco": "Se practica de forma individual",
      "Vela": "Se practica en el agua",
      "Squash": "Se juega con pelota o raqueta",
      "Padel": "Se juega con pelota o raqueta",
      "Cricket": "Se juega con pelota y en equipo",
      "Bowling": "Se juega en interiores",
      "Billar": "Se juega en interiores",
      "Ajedrez": "No requiere esfuerzo físico intenso",
      "Automovilismo": "Se practica con un vehículo",
      "Motociclismo": "Se practica con un vehículo",
      "Remo": "Se practica en el agua",
      "Skateboarding": "Se practica con un vehículo o rodado",
      "Motocross": "Se practica con un vehículo",
      "Softbol": "Se juega con pelota y en equipo",
      "Waterpolo": "Se practica en el agua",
      "Curling": "Se practica sobre hielo",
      "Bádminton": "Se juega con pelota o raqueta",
    },
    words: [
      "Fútbol",
      "Basketball",
      "Tenis",
      "Natación",
      "Atletismo",
      "Boxeo",
      "Ciclismo",
      "Golf",
      "Rugby",
      "Béisbol",
      "Volleyball",
      "Handball",
      "Hockey sobre hielo",
      "Esquí",
      "Snowboard",
      "Surf",
      "Escalada",
      "Triatlón",
      "Esgrima",
      "Judo",
      "Karate",
      "Taekwondo",
      "Lucha libre",
      "Halterofilia",
      "Gimnasia artística",
      "Patinaje artístico",
      "Polo",
      "Tiro con arco",
      "Vela",
      "Squash",
      "Padel",
      "Cricket",
      "Bowling",
      "Billar",
      "Ajedrez",
      "Automovilismo",
      "Motociclismo",
      "Remo",
      "Skateboarding",
      "Motocross",
      "Softbol",
      "Waterpolo",
      "Curling",
      "Bádminton",
    ],
  },
  musicos: {
    label: "Músicos Famosos",
    icon: "🎸",
    hints: {
      "Michael Jackson": "Es un solista de pop",
      "Elvis Presley": "Es un solista de rock o pop clásico",
      "The Beatles": "Es una banda de rock",
      "Queen": "Es una banda de rock",
      "Rolling Stones": "Es una banda de rock",
      "Led Zeppelin": "Es una banda de rock",
      "Pink Floyd": "Es una banda de rock",
      "David Bowie": "Es un solista de rock o pop",
      "Bob Dylan": "Es un solista de rock o folk",
      "Jimi Hendrix": "Es un solista de rock",
      "Madonna": "Es una solista de pop",
      "Whitney Houston": "Es una solista de pop",
      "Beyoncé": "Es una solista de pop o R&B",
      "Rihanna": "Es una solista de pop o R&B",
      "Shakira": "Es una solista de pop latino",
      "Taylor Swift": "Es una solista de pop",
      "Ariana Grande": "Es una solista de pop",
      "Lady Gaga": "Es una solista de pop",
      "Adele": "Es una solista de pop",
      "Ed Sheeran": "Es un solista de pop",
      "Bruno Mars": "Es un solista de pop",
      "The Weeknd": "Es un solista de pop o R&B",
      "Eminem": "Es un solista de rap",
      "Jay-Z": "Es un solista de rap",
      "Kanye West": "Es un solista de rap",
      "Drake": "Es un solista de rap o R&B",
      "Bad Bunny": "Es un solista de música urbana latina",
      "J Balvin": "Es un solista de música urbana latina",
      "Daddy Yankee": "Es un solista de música urbana latina",
      "Luis Fonsi": "Es un solista de pop latino",
      "Celia Cruz": "Es una solista de música latina clásica",
      "Julio Iglesias": "Es un solista de música latina clásica",
      "Chayanne": "Es un solista de pop latino",
      "Ricky Martin": "Es un solista de pop latino",
      "Gloria Estefan": "Es una solista de pop latino",
      "Karol G": "Es una solista de música urbana latina",
      "Maluma": "Es un solista de música urbana latina",
      "Ozuna": "Es un solista de música urbana latina",
      "Feid": "Es un solista de música urbana latina",
      "Peso Pluma": "Es un solista de música urbana latina",
      "Rosalía": "Es una solista de pop o música urbana",
      "Charly García": "Es un solista o líder de banda de rock latino",
      "Gustavo Cerati": "Es un solista o líder de banda de rock latino",
      "Fito Páez": "Es un solista de rock o pop latino",
      "Luis Miguel": "Es un solista de música latina clásica",
      "Selena Quintanilla": "Es una solista de música latina clásica",
      "Juan Gabriel": "Es un solista de música latina clásica",
      "Vicente Fernández": "Es un solista de música latina clásica",
      "Frank Sinatra": "Es un solista de música clásica anglosajona",
      "Freddie Mercury": "Es un integrante de una banda de rock",
      "John Lennon": "Es un integrante de una banda de rock",
      "Paul McCartney": "Es un integrante de una banda de rock",
    },
    words: [
      "Michael Jackson",
      "Elvis Presley",
      "The Beatles",
      "Queen",
      "Rolling Stones",
      "Led Zeppelin",
      "Pink Floyd",
      "David Bowie",
      "Bob Dylan",
      "Jimi Hendrix",
      "Madonna",
      "Whitney Houston",
      "Beyoncé",
      "Rihanna",
      "Shakira",
      "Taylor Swift",
      "Ariana Grande",
      "Lady Gaga",
      "Adele",
      "Ed Sheeran",
      "Bruno Mars",
      "The Weeknd",
      "Eminem",
      "Jay-Z",
      "Kanye West",
      "Drake",
      "Bad Bunny",
      "J Balvin",
      "Daddy Yankee",
      "Luis Fonsi",
      "Celia Cruz",
      "Julio Iglesias",
      "Chayanne",
      "Ricky Martin",
      "Gloria Estefan",
      "Karol G",
      "Maluma",
      "Ozuna",
      "Feid",
      "Peso Pluma",
      "Rosalía",
      "Charly García",
      "Gustavo Cerati",
      "Fito Páez",
      "Luis Miguel",
      "Selena Quintanilla",
      "Juan Gabriel",
      "Vicente Fernández",
      "Frank Sinatra",
      "Freddie Mercury",
      "John Lennon",
      "Paul McCartney",
    ],
  },
  superheroes: {
    label: "Superhéroes y Villanos",
    icon: "🦸",
    hints: {
      "Superman": "Es un héroe con superpoderes",
      "Batman": "Es un héroe sin superpoderes propios",
      "Spider-Man": "Es un héroe con superpoderes",
      "Iron Man": "Es un héroe sin superpoderes propios",
      "Capitán América": "Es un héroe con habilidades físicas mejoradas",
      "Thor": "Es un héroe con superpoderes",
      "Hulk": "Es un héroe con superpoderes",
      "Wonder Woman": "Es una heroína con superpoderes",
      "Flash": "Es un héroe con superpoderes",
      "Aquaman": "Es un héroe con superpoderes",
      "Linterna Verde": "Es un héroe con superpoderes",
      "Black Widow": "Es una heroína sin superpoderes propios",
      "Doctor Strange": "Es un héroe con habilidades mágicas",
      "Pantera Negra": "Es un héroe sin superpoderes propios",
      "Capitana Marvel": "Es una heroína con superpoderes",
      "Deadpool": "Es un héroe con superpoderes",
      "Wolverine": "Es un héroe con superpoderes",
      "Profesor X": "Es un héroe con superpoderes",
      "Mystique": "Es un personaje con superpoderes",
      "Joker": "Es un villano sin superpoderes propios",
      "Lex Luthor": "Es un villano sin superpoderes propios",
      "Thanos": "Es un villano con superpoderes",
      "Loki": "Es un villano con habilidades mágicas",
      "Venom": "Es un villano con superpoderes",
      "Magneto": "Es un villano con superpoderes",
      "Guasón": "Es un villano sin superpoderes propios",
      "Harley Quinn": "Es un personaje sin superpoderes propios",
      "Darkseid": "Es un villano con superpoderes",
    },
    words: [
      "Superman",
      "Batman",
      "Spider-Man",
      "Iron Man",
      "Capitán América",
      "Thor",
      "Hulk",
      "Wonder Woman",
      "Flash",
      "Aquaman",
      "Linterna Verde",
      "Black Widow",
      "Doctor Strange",
      "Pantera Negra",
      "Capitana Marvel",
      "Deadpool",
      "Wolverine",
      "Profesor X",
      "Mystique",
      "Joker",
      "Lex Luthor",
      "Thanos",
      "Loki",
      "Venom",
      "Magneto",
      "Guasón",
      "Harley Quinn",
      "Darkseid",
    ],
  },
  videojuegos: {
    label: "Videojuegos",
    icon: "🎮",
    hints: {
      "Minecraft": "Se puede construir y explorar un mundo abierto",
      "Fortnite": "Es un juego de disparos multijugador",
      "Among Us": "Se juega en grupo tratando de descubrir un impostor",
      "The Legend of Zelda": "Es un juego de aventura y exploración",
      "Super Mario Bros": "Es un juego de plataformas",
      "Grand Theft Auto": "Es un juego de mundo abierto",
      "Call of Duty": "Es un juego de disparos",
      "FIFA": "Es un juego de deportes",
      "The Last of Us": "Es un juego de aventura y narrativa",
      "God of War": "Es un juego de acción y aventura",
      "Red Dead Redemption": "Es un juego de mundo abierto",
      "Pokémon": "Se pueden atrapar y entrenar criaturas",
      "Animal Crossing": "Es un juego de simulación de vida",
      "League of Legends": "Se juega en equipo en línea",
      "Valorant": "Es un juego de disparos multijugador",
      "Counter-Strike": "Es un juego de disparos multijugador",
      "Fall Guys": "Es un juego multijugador de plataformas y obstáculos",
      "Roblox": "Permite crear y jugar minijuegos hechos por usuarios",
      "Tetris": "Es un juego de rompecabezas",
      "Sonic": "Es un juego de plataformas",
      "Street Fighter": "Es un juego de peleas uno contra uno",
      "Mortal Kombat": "Es un juego de peleas uno contra uno",
      "The Sims": "Es un juego de simulación de vida",
      "Overwatch": "Se juega en equipo en línea",
      "Halo": "Es un juego de disparos",
      "Resident Evil": "Es un juego de terror y supervivencia",
      "Elden Ring": "Es un juego de rol y aventura",
      "Genshin Impact": "Es un juego de rol y mundo abierto",
    },
    words: [
      "Minecraft",
      "Fortnite",
      "Among Us",
      "The Legend of Zelda",
      "Super Mario Bros",
      "Grand Theft Auto",
      "Call of Duty",
      "FIFA",
      "The Last of Us",
      "God of War",
      "Red Dead Redemption",
      "Pokémon",
      "Animal Crossing",
      "League of Legends",
      "Valorant",
      "Counter-Strike",
      "Fall Guys",
      "Roblox",
      "Tetris",
      "Sonic",
      "Street Fighter",
      "Mortal Kombat",
      "The Sims",
      "Overwatch",
      "Halo",
      "Resident Evil",
      "Elden Ring",
      "Genshin Impact",
    ],
  },
  peliculas: {
    label: "Películas Famosas",
    icon: "🎥",
    hints: {
      "Titanic": "Es un drama romántico",
      "El Padrino": "Es un drama sobre el crimen organizado",
      "Star Wars": "Es una película de ciencia ficción",
      "Jurassic Park": "Es una película de aventura y ciencia ficción",
      "El Señor de los Anillos": "Es una película de fantasía",
      "Harry Potter": "Es una película de fantasía",
      "Avatar": "Es una película de ciencia ficción",
      "Los Vengadores": "Es una película de superhéroes",
      "El Rey León": "Es una película animada",
      "Forrest Gump": "Es un drama",
      "Matrix": "Es una película de ciencia ficción y acción",
      "Pulp Fiction": "Es un drama sobre el crimen",
      "El Origen": "Es una película de ciencia ficción",
      "Interestelar": "Es una película de ciencia ficción",
      "Coco": "Es una película animada",
      "Frozen": "Es una película animada",
      "Toy Story": "Es una película animada",
      "Shrek": "Es una película animada",
      "Joker": "Es un drama sobre un villano de cómic",
      "Parásitos": "Es un drama con tintes de suspenso",
      "La La Land": "Es un musical romántico",
      "Gladiador": "Es una película de acción histórica",
      "Rocky": "Es una película de deporte y drama",
      "Volver al Futuro": "Es una película de ciencia ficción y comedia",
      "Jaws": "Es una película de suspenso",
      "E.T.": "Es una película de ciencia ficción y aventura",
      "Los Increíbles": "Es una película animada",
    },
    words: [
      "Titanic",
      "El Padrino",
      "Star Wars",
      "Jurassic Park",
      "El Señor de los Anillos",
      "Harry Potter",
      "Avatar",
      "Los Vengadores",
      "El Rey León",
      "Forrest Gump",
      "Matrix",
      "Pulp Fiction",
      "El Origen",
      "Interestelar",
      "Coco",
      "Frozen",
      "Toy Story",
      "Shrek",
      "Joker",
      "Parásitos",
      "La La Land",
      "Gladiador",
      "Rocky",
      "Volver al Futuro",
      "Jaws",
      "E.T.",
      "Los Increíbles",
    ],
  },
  series: {
    label: "Series de TV",
    icon: "📺",
    hints: {
      "Friends": "Es una comedia de situación",
      "Breaking Bad": "Es un drama sobre el crimen",
      "Game of Thrones": "Es una serie de fantasía",
      "Stranger Things": "Es una serie de ciencia ficción y misterio",
      "The Office": "Es una comedia de situación",
      "La Casa de Papel": "Es un drama sobre un robo",
      "Los Simpson": "Es una serie animada",
      "Grey's Anatomy": "Es un drama médico",
      "How I Met Your Mother": "Es una comedia de situación",
      "The Walking Dead": "Es una serie de terror y supervivencia",
      "Peaky Blinders": "Es un drama sobre el crimen",
      "Narcos": "Es un drama sobre el crimen",
      "Black Mirror": "Es una serie de ciencia ficción",
      "The Crown": "Es un drama histórico",
      "Better Call Saul": "Es un drama sobre el crimen",
      "Sherlock": "Es una serie de misterio y detectives",
      "Dark": "Es una serie de ciencia ficción y misterio",
      "Élite": "Es un drama juvenil",
      "Vikingos": "Es un drama histórico",
      "El Chavo del 8": "Es una comedia de situación",
      "Rick and Morty": "Es una serie animada",
      "South Park": "Es una serie animada",
      "Bob Esponja": "Es una serie animada",
      "Euphoria": "Es un drama juvenil",
      "Wednesday": "Es una serie juvenil de misterio",
    },
    words: [
      "Friends",
      "Breaking Bad",
      "Game of Thrones",
      "Stranger Things",
      "The Office",
      "La Casa de Papel",
      "Los Simpson",
      "Grey's Anatomy",
      "How I Met Your Mother",
      "The Walking Dead",
      "Peaky Blinders",
      "Narcos",
      "Black Mirror",
      "The Crown",
      "Better Call Saul",
      "Sherlock",
      "Dark",
      "Élite",
      "Vikingos",
      "El Chavo del 8",
      "Rick and Morty",
      "South Park",
      "Bob Esponja",
      "Euphoria",
      "Wednesday",
    ],
  },
  profesiones: {
    label: "Profesiones",
    icon: "💼",
    hints: {
      "Médico": "Es una profesión relacionada con la salud",
      "Enfermero": "Es una profesión relacionada con la salud",
      "Bombero": "Es una profesión de emergencia o rescate",
      "Policía": "Es una profesión de seguridad",
      "Abogado": "Requiere estudios universitarios de larga duración",
      "Maestro": "Trabaja formando a otras personas",
      "Ingeniero": "Requiere estudios universitarios de larga duración",
      "Arquitecto": "Requiere estudios universitarios de larga duración",
      "Piloto": "Trabaja en el transporte",
      "Chef": "Trabaja preparando comida",
      "Peluquero": "Es un oficio manual",
      "Electricista": "Es un oficio manual",
      "Plomero": "Es un oficio manual",
      "Carpintero": "Es un oficio manual",
      "Veterinario": "Es una profesión relacionada con la salud",
      "Psicólogo": "Es una profesión relacionada con la salud",
      "Periodista": "Trabaja comunicando información",
      "Fotógrafo": "Trabaja en un ámbito creativo",
      "Actor": "Trabaja en un ámbito creativo",
      "Músico": "Trabaja en un ámbito creativo",
      "Programador": "Requiere conocimientos técnicos de tecnología",
      "Contador": "Requiere estudios universitarios de larga duración",
      "Dentista": "Es una profesión relacionada con la salud",
      "Farmacéutico": "Es una profesión relacionada con la salud",
      "Albañil": "Es un oficio manual",
      "Panadero": "Trabaja preparando comida",
      "Mecánico": "Es un oficio manual",
      "Astronauta": "Requiere un entrenamiento muy especializado y poco común",
    },
    words: [
      "Médico",
      "Enfermero",
      "Bombero",
      "Policía",
      "Abogado",
      "Maestro",
      "Ingeniero",
      "Arquitecto",
      "Piloto",
      "Chef",
      "Peluquero",
      "Electricista",
      "Plomero",
      "Carpintero",
      "Veterinario",
      "Psicólogo",
      "Periodista",
      "Fotógrafo",
      "Actor",
      "Músico",
      "Programador",
      "Contador",
      "Dentista",
      "Farmacéutico",
      "Albañil",
      "Panadero",
      "Mecánico",
      "Astronauta",
    ],
  },
  marcas: {
    label: "Marcas Famosas",
    icon: "🏷️",
    hints: {
      "Coca-Cola": "Es una marca de bebidas",
      "Pepsi": "Es una marca de bebidas",
      "McDonald's": "Es una marca de comida rápida",
      "Nike": "Es una marca de ropa o calzado deportivo",
      "Adidas": "Es una marca de ropa o calzado deportivo",
      "Apple": "Es una marca de tecnología",
      "Samsung": "Es una marca de tecnología",
      "Google": "Es una marca de tecnología",
      "Amazon": "Es una marca de tecnología o comercio",
      "Netflix": "Es una marca de entretenimiento",
      "Disney": "Es una marca de entretenimiento",
      "Ferrari": "Es una marca de vehículos",
      "Toyota": "Es una marca de vehículos",
      "BMW": "Es una marca de vehículos",
      "Starbucks": "Es una marca de bebidas",
      "IKEA": "Es una marca de muebles o el hogar",
      "Gucci": "Es una marca de moda o lujo",
      "Chanel": "Es una marca de moda o lujo",
      "Rolex": "Es una marca de moda o lujo",
      "Lego": "Es una marca de juguetes o juegos",
      "Sony": "Es una marca de tecnología o entretenimiento",
      "Nintendo": "Es una marca de juguetes o juegos",
      "PlayStation": "Es una marca de juguetes o juegos",
      "Xbox": "Es una marca de juguetes o juegos",
      "Instagram": "Es una marca de tecnología o redes sociales",
      "WhatsApp": "Es una marca de tecnología o redes sociales",
      "TikTok": "Es una marca de tecnología o redes sociales",
    },
    words: [
      "Coca-Cola",
      "Pepsi",
      "McDonald's",
      "Nike",
      "Adidas",
      "Apple",
      "Samsung",
      "Google",
      "Amazon",
      "Netflix",
      "Disney",
      "Ferrari",
      "Toyota",
      "BMW",
      "Starbucks",
      "IKEA",
      "Gucci",
      "Chanel",
      "Rolex",
      "Lego",
      "Sony",
      "Nintendo",
      "PlayStation",
      "Xbox",
      "Instagram",
      "WhatsApp",
      "TikTok",
    ],
  },
  lugares: {
    label: "Lugares Turísticos",
    icon: "🗺️",
    hints: {
      "Torre Eiffel": "Es una construcción humana en Europa",
      "Coliseo Romano": "Es una construcción humana antigua",
      "Machu Picchu": "Es una construcción humana antigua en Sudamérica",
      "Gran Muralla China": "Es una construcción humana antigua",
      "Taj Mahal": "Es una construcción humana en Asia",
      "Cataratas del Iguazú": "Es un lugar natural en Sudamérica",
      "Estatua de la Libertad": "Es una construcción humana en América",
      "Torre de Pisa": "Es una construcción humana en Europa",
      "Sagrada Familia": "Es una construcción humana religiosa en Europa",
      "Big Ben": "Es una construcción humana en Europa",
      "Cristo Redentor": "Es una construcción humana religiosa en Sudamérica",
      "Pirámides de Egipto": "Es una construcción humana antigua",
      "Times Square": "Es un lugar urbano moderno en América",
      "Las Vegas": "Es un lugar urbano moderno en América",
      "Disneyland": "Es un lugar de entretenimiento moderno",
      "Chichén Itzá": "Es una construcción humana antigua en América",
      "Salar de Uyuni": "Es un lugar natural en Sudamérica",
      "Islas Galápagos": "Es un lugar natural en Sudamérica",
      "Gran Cañón": "Es un lugar natural en América del Norte",
      "Muralla de Berlín": "Es una construcción humana moderna en Europa",
      "Kremlin": "Es una construcción humana en Europa",
      "Ópera de Sídney": "Es una construcción humana moderna en Oceanía",
      "Monte Everest": "Es un lugar natural en Asia",
      "Amazonas": "Es un lugar natural en Sudamérica",
    },
    words: [
      "Torre Eiffel",
      "Coliseo Romano",
      "Machu Picchu",
      "Gran Muralla China",
      "Taj Mahal",
      "Cataratas del Iguazú",
      "Estatua de la Libertad",
      "Torre de Pisa",
      "Sagrada Familia",
      "Big Ben",
      "Cristo Redentor",
      "Pirámides de Egipto",
      "Times Square",
      "Las Vegas",
      "Disneyland",
      "Chichén Itzá",
      "Salar de Uyuni",
      "Islas Galápagos",
      "Gran Cañón",
      "Muralla de Berlín",
      "Kremlin",
      "Ópera de Sídney",
      "Monte Everest",
      "Amazonas",
    ],
  },
};
