// ─── Game Data ───────────────────────────────────────────────────────────────
export interface Category {
  id: string;
  label: string;
  icon: string;
}

export const DEFAULT_CATEGORIES: Category[] = [
  { id: "nombre", label: "Nombre", icon: "🧑" },
  { id: "apellido", label: "Apellido", icon: "👪" },
  { id: "pais", label: "País", icon: "🌍" },
  { id: "ciudad", label: "Ciudad", icon: "🏙️" },
  { id: "animal", label: "Animal", icon: "🦁" },
  { id: "color", label: "Color", icon: "🎨" },
  { id: "comida", label: "Comida", icon: "🍕" },
  { id: "fruta", label: "Fruta o Verdura", icon: "🍉" },
  { id: "objeto", label: "Objeto", icon: "🪑" },
  { id: "marca", label: "Marca", icon: "🏷️" },
  { id: "peliserie", label: "Película o Serie", icon: "🎬" },
  { id: "profesion", label: "Profesión", icon: "💼" },
  { id: "deporte", label: "Deporte", icon: "🏅" },
  { id: "cuerpo", label: "Parte del Cuerpo", icon: "🖐️" },
  { id: "cantante", label: "Cantante o Banda", icon: "🎤" },
  { id: "equipo", label: "Equipo de Fútbol", icon: "⚽" },
  { id: "peliactor", label: "Actor o Actriz", icon: "🎭" },
  { id: "serie_animada", label: "Serie o Película Animada", icon: "📺" },
  { id: "personaje", label: "Personaje Ficticio", icon: "🦸" },
  { id: "videojuego", label: "Videojuego", icon: "🎮" },
  { id: "instrumento", label: "Instrumento Musical", icon: "🎸" },
  { id: "juego_mesa", label: "Juego de Mesa o Cartas", icon: "🎲" },
  { id: "bebida", label: "Bebida", icon: "🥤" },
  { id: "postre", label: "Postre o Dulce", icon: "🍰" },
  { id: "medio_transporte", label: "Medio de Transporte", icon: "🚗" },
  { id: "herramienta", label: "Herramienta", icon: "🔧" },
  { id: "prenda", label: "Prenda de Ropa", icon: "👕" },
  { id: "mueble", label: "Mueble", icon: "🛋️" },
  { id: "planta", label: "Planta o Flor", icon: "🌿" },
  { id: "insecto", label: "Insecto o Bicho", icon: "🐛" },
  { id: "rio_mar", label: "Río, Mar o Lago", icon: "🌊" },
  { id: "montana", label: "Montaña o Volcán", icon: "🏔️" },
  { id: "planeta", label: "Planeta o Cuerpo Celeste", icon: "🪐" },
  { id: "materia_escolar", label: "Materia Escolar", icon: "📚" },
  { id: "superheroe", label: "Superhéroe o Villano", icon: "🦹" },
  { id: "dibujo_animado", label: "Dibujo Animado", icon: "🐭" },
  { id: "red_social", label: "Red Social o App", icon: "📱" },
  { id: "signo_zodiaco", label: "Signo del Zodíaco", icon: "♈" },
  { id: "enfermedad", label: "Enfermedad o Síntoma", icon: "🤒" },
  { id: "arma", label: "Arma (histórica o de juego)", icon: "🗡️" },
  { id: "moneda", label: "Moneda", icon: "💰" },
  { id: "idioma", label: "Idioma", icon: "🗣️" },
  { id: "festividad", label: "Festividad o Celebración", icon: "🎉" },
  { id: "programa_tv", label: "Programa de TV", icon: "📻" },
  { id: "cientifico", label: "Científico o Inventor", icon: "🔬" },
  { id: "juguete", label: "Juguete", icon: "🧸" },
  { id: "utensilio_cocina", label: "Utensilio de Cocina", icon: "🍴" },
  { id: "electrodomestico", label: "Electrodoméstico", icon: "🔌" },
  { id: "dinosaurio", label: "Dinosaurio", icon: "🦖" },
  { id: "pez", label: "Pez o Animal Marino", icon: "🐠" },
  { id: "ave", label: "Ave", icon: "🦜" },
  { id: "postre_regional", label: "Comida Típica Argentina", icon: "🥟" },
  { id: "condimento", label: "Condimento o Especia", icon: "🧂" },
  { id: "queso", label: "Tipo de Queso o Fiambre", icon: "🧀" },
  { id: "trago", label: "Trago o Cóctel", icon: "🍹" },
  { id: "app_celular", label: "App del Celular", icon: "📲" },
  { id: "canal_youtuber", label: "Youtuber o Streamer", icon: "📹" },
  { id: "meme", label: "Meme Famoso", icon: "😂" },
  { id: "cancion", label: "Canción o Tema Musical", icon: "🎵" },
  { id: "genero_musical", label: "Género Musical", icon: "🎧" },
  { id: "baile", label: "Tipo de Baile", icon: "💃" },
  { id: "profesion_rara", label: "Profesión Rara o Poco Común", icon: "🕵️" },
  { id: "excusa_tarde", label: "Excusa para Llegar Tarde", icon: "⏰" },
  { id: "cosa_cartera", label: "Cosa que hay en una Cartera o Mochila", icon: "👜" },
  { id: "cosa_heladera", label: "Cosa que hay en la Heladera", icon: "🧊" },
  { id: "insulto_suave", label: "Insulto Suave o Cargada Amistosa", icon: "😜" },
  { id: "cosa_casamiento", label: "Cosa que se hace en un Casamiento", icon: "💍" },
  { id: "cosa_asado", label: "Cosa Típica de un Asado", icon: "🍖" },
  { id: "cosa_vacaciones", label: "Cosa que Llevás de Vacaciones", icon: "🧳" },
  { id: "cosa_no_falta_bolso_gym", label: "Cosa que no Falta en un Bolso de Gimnasio", icon: "🏋️" },
  { id: "nombre_mascota", label: "Apodo de Mascota", icon: "🐶" },
  { id: "sonido_animal", label: "Sonido que hace un Animal", icon: "🔊" },
  { id: "cosa_da_verguenza", label: "Cosa que da Vergüenza Ajena", icon: "🙈" },
  { id: "cosa_dice_abuela", label: "Cosa que Diría una Abuela", icon: "👵" },
  { id: "personaje_dibujitos_infancia", label: "Personaje de Dibujitos de tu Infancia", icon: "📼" },
  { id: "villano_pelicula", label: "Villano de Película", icon: "😈" },
  { id: "cosa_no_deberia_reirse", label: "Cosa de la que no Deberías Reírte pero te Da Risa", icon: "🤭" },
  { id: "app_citas", label: "Frase de Perfil de App de Citas", icon: "💌" },
  { id: "cosa_oficina", label: "Cosa que hay en una Oficina", icon: "🖇️" },
  { id: "signo_transito", label: "Señal o Cartel de Tránsito", icon: "🚸" },
  { id: "titulo_pelicula_terror", label: "Título de Película de Terror", icon: "🔪" },
  { id: "cosa_no_regalar", label: "Cosa que Nunca Regalarías", icon: "🎁" },
  { id: "excusa_no_estudiaste", label: "Excusa por no Haber Estudiado", icon: "📖" },
  { id: "cosa_hospital", label: "Cosa que hay en un Hospital", icon: "🏥" },
  { id: "grito_gol", label: "Cosa que Grita un Hincha en la Cancha", icon: "🗣️" },
  { id: "objeto_perdido", label: "Objeto que Siempre se Pierde en tu Casa", icon: "🔍" },
  { id: "cosa_dice_jefe", label: "Frase Típica de un Jefe", icon: "👔" },
  { id: "cosa_relacion_toxica", label: "Señal de una Relación Tóxica", icon: "💔" },
  { id: "capital", label: "Capital de un País", icon: "🏛️" },
  { id: "raza_perro", label: "Raza de Perro", icon: "🐕" },
  { id: "constelacion", label: "Constelación", icon: "✨" },
  { id: "elemento_quimico", label: "Elemento Químico", icon: "⚗️" },
  { id: "gadget_tecnologico", label: "Gadget o Aparato Tecnológico", icon: "💻" },
  { id: "frase_ex", label: "Frase que Diría un Ex", icon: "🙄" },
  { id: "frase_mama_enojada", label: "Frase que Grita una Mamá Enojada", icon: "😡" },
  { id: "frase_grupo_whatsapp", label: "Frase Típica de un Grupo de WhatsApp Familiar", icon: "📱" },
  { id: "mentira_blanca", label: "Mentira Piadosa que Todos Dijimos Alguna Vez", icon: "🤥" },
  { id: "frase_borracho", label: "Frase Típica de Alguien Borracho", icon: "🍺" },
  { id: "cosa_dice_profe", label: "Frase Típica de un Profesor", icon: "🧑‍🏫" },
  { id: "frase_venta_usado", label: "Frase de un Aviso de Venta de Usado", icon: "🏷️" },
  { id: "cosa_no_falta_casa_abuela", label: "Cosa que no Falta en la Casa de la Abuela", icon: "🏡" },
  { id: "cosa_dice_influencer", label: "Frase Típica de un Influencer", icon: "🤳" },
  { id: "excusa_no_ir_gimnasio", label: "Excusa para no Ir al Gimnasio", icon: "🛌" },
  { id: "excusa_no_contestar", label: "Excusa por no Contestar el Teléfono", icon: "📵" },
  { id: "cosa_dice_taxi", label: "Cosa que te Dice un Taxista Charlatán", icon: "🚕" },
  { id: "cosa_grita_hincha_perdiendo", label: "Cosa que Grita un Hincha cuando va Perdiendo", icon: "😩" },
  { id: "titulo_pelicula_mala", label: "Título Inventado de una Película Mala", icon: "🎬" },
  { id: "nombre_pizza_rara", label: "Combinación Rara para una Pizza", icon: "🍕" },
  { id: "cosa_no_deberia_llevar_avion", label: "Cosa que Nunca Deberías Llevar en un Avión", icon: "🛫" },
  { id: "cosa_asusta_sin_razon", label: "Cosa que da Miedo sin Motivo Real", icon: "😱" },
  { id: "superpoder_inutil", label: "Superpoder Completamente Inútil", icon: "🦸‍♂️" },
  { id: "nombre_perfume_ridiculo", label: "Título Ridículo para un Perfume", icon: "🧴" },
  { id: "cosa_grupo_amigos", label: "Cosa que Siempre Hace 'el del Grupo'", icon: "👥" },
  { id: "frase_vecino_ruidoso", label: "Frase de un Vecino Ruidoso Enojado", icon: "🏠" },
  { id: "cosa_lleva_sobrepeso_valija", label: "Cosa que Sobra en la Valija al Volver de Viaje", icon: "🧳" },
  { id: "titulo_grupo_whatsapp_curso", label: "Título para un Grupo de WhatsApp del Curso", icon: "💬" },
  { id: "cosa_no_dirias_entrevista", label: "Cosa que Jamás Dirías en una Entrevista de Trabajo", icon: "🧑‍💼" },
  { id: "razon_falta_trabajo", label: "Excusa para Faltar al Trabajo", icon: "🤒" },
  { id: "cosa_dice_medico", label: "Frase Típica de un Médico", icon: "🩺" },
  { id: "cosa_hace_gato", label: "Cosa Rara que Hace un Gato", icon: "🐱" },
  { id: "sonido_molesto", label: "Sonido que Todos Odiamos Escuchar", icon: "🦻" },
  { id: "cosa_no_falta_fiesta_15", label: "Cosa que no Falta en una Fiesta de 15", icon: "🎂" },
];

export const LETTERS: string[] = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "Ñ",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];
