// ─── Game Data ───────────────────────────────────────────────────────────────
export interface Category {
  id: string;
  label: string;
  icon: string;
}

export const DEFAULT_CATEGORIES: Category[] = [
  { id: "nombre", label: "Nombre", icon: "🧑" },
  { id: "apellido", label: "Apellido", icon: "👪" },
  { id: "pais", label: "País", icon: "🌍" },
  { id: "ciudad", label: "Ciudad", icon: "🏙️" },
  { id: "animal", label: "Animal", icon: "🦁" },
  { id: "color", label: "Color", icon: "🎨" },
  { id: "comida", label: "Comida", icon: "🍕" },
  { id: "fruta", label: "Fruta o Verdura", icon: "🍉" },
  { id: "objeto", label: "Objeto", icon: "🪑" },
  { id: "marca", label: "Marca", icon: "🏷️" },
  { id: "peliserie", label: "Película o Serie", icon: "🎬" },
  { id: "profesion", label: "Profesión", icon: "💼" },
  { id: "deporte", label: "Deporte", icon: "🏅" },
  { id: "cuerpo", label: "Parte del Cuerpo", icon: "🖐️" },
  { id: "cantante", label: "Cantante o Banda", icon: "🎤" },
  { id: "equipo", label: "Equipo de Fútbol", icon: "⚽" },
  { id: "peliactor", label: "Actor o Actriz", icon: "🎭" },
  { id: "serie_animada", label: "Serie o Película Animada", icon: "📺" },
  { id: "personaje", label: "Personaje Ficticio", icon: "🦸" },
  { id: "videojuego", label: "Videojuego", icon: "🎮" },
  { id: "instrumento", label: "Instrumento Musical", icon: "🎸" },
  { id: "juego_mesa", label: "Juego de Mesa o Cartas", icon: "🎲" },
  { id: "bebida", label: "Bebida", icon: "🥤" },
  { id: "postre", label: "Postre o Dulce", icon: "🍰" },
  { id: "medio_transporte", label: "Medio de Transporte", icon: "🚗" },
  { id: "herramienta", label: "Herramienta", icon: "🔧" },
  { id: "prenda", label: "Prenda de Ropa", icon: "👕" },
  { id: "mueble", label: "Mueble", icon: "🛋️" },
  { id: "planta", label: "Planta o Flor", icon: "🌿" },
  { id: "insecto", label: "Insecto o Bicho", icon: "🐛" },
  { id: "rio_mar", label: "Río, Mar o Lago", icon: "🌊" },
  { id: "montana", label: "Montaña o Volcán", icon: "🏔️" },
  { id: "planeta", label: "Planeta o Cuerpo Celeste", icon: "🪐" },
  { id: "materia_escolar", label: "Materia Escolar", icon: "📚" },
  { id: "superheroe", label: "Superhéroe o Villano", icon: "🦹" },
  { id: "dibujo_animado", label: "Dibujo Animado", icon: "🐭" },
  { id: "red_social", label: "Red Social o App", icon: "📱" },
  { id: "signo_zodiaco", label: "Signo del Zodíaco", icon: "♈" },
  { id: "enfermedad", label: "Enfermedad o Síntoma", icon: "🤒" },
  { id: "arma", label: "Arma (histórica o de juego)", icon: "🗡️" },
  { id: "moneda", label: "Moneda", icon: "💰" },
  { id: "idioma", label: "Idioma", icon: "🗣️" },
  { id: "festividad", label: "Festividad o Celebración", icon: "🎉" },
  { id: "programa_tv", label: "Programa de TV", icon: "📻" },
  { id: "cientifico", label: "Científico o Inventor", icon: "🔬" },
];

export const LETTERS: string[] = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "Ñ",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];
