// ─── Game Data ───────────────────────────────────────────────────────────────
// Word pools for "¿Quién Soy?"'s "categorías" word source (the alternative to
// "sugerida", where players write their own words instead) — same
// Record<string, Category> shape as impostor-data, just without hints since
// nobody here needs a bluffing clue.
export interface Category {
  label: string;
  icon: string;
  words: string[];
}

export const CATEGORIES: Record<string, Category> = {
  "personajes-famosos": {
    label: "Personajes Famosos",
    icon: "🌟",
    words: [
      "Lionel Messi",
      "Diego Maradona",
      "Shakira",
      "Freddie Mercury",
      "Albert Einstein",
      "Leonardo da Vinci",
      "Frida Kahlo",
      "Charly García",
      "Michael Jackson",
      "Elvis Presley",
      "Marilyn Monroe",
      "Charlie Chaplin",
      "Pablo Picasso",
      "Steve Jobs",
      "Walt Disney",
      "Beyoncé",
      "Madonna",
      "Bad Bunny",
      "Cristiano Ronaldo",
      "Serena Williams",
    ],
  },
  "personajes-de-ficcion": {
    label: "Personajes de Ficción",
    icon: "🎬",
    words: [
      "Harry Potter",
      "Batman",
      "Spider-Man",
      "Homero Simpson",
      "Shrek",
      "Woody",
      "Mickey Mouse",
      "Darth Vader",
      "Sherlock Holmes",
      "Frodo Bolsón",
      "James Bond",
      "Indiana Jones",
      "Forrest Gump",
      "El Joker",
      "Wonder Woman",
      "Gandalf",
      "Elsa",
      "Buzz Lightyear",
      "Pikachu",
      "Chapulín Colorado",
    ],
  },
  animales: {
    label: "Animales",
    icon: "🦁",
    words: [
      "León",
      "Elefante",
      "Delfín",
      "Águila",
      "Pingüino",
      "Tiburón",
      "Jirafa",
      "Canguro",
      "Pulpo",
      "Oso Panda",
      "Cocodrilo",
      "Búho",
      "Tortuga",
      "Zorro",
      "Lobo",
      "Camaleón",
      "Koala",
      "Murciélago",
      "Flamenco",
      "Erizo",
    ],
  },
  profesiones: {
    label: "Profesiones",
    icon: "👷",
    words: [
      "Médico",
      "Bombero",
      "Policía",
      "Maestro",
      "Astronauta",
      "Piloto",
      "Chef",
      "Abogado",
      "Arquitecto",
      "Periodista",
      "Veterinario",
      "Dentista",
      "Peluquero",
      "Fotógrafo",
      "Electricista",
      "Cartero",
      "Jardinero",
      "Actor",
      "Músico",
      "Programador",
    ],
  },
  superheroes: {
    label: "Superhéroes y Villanos",
    icon: "🦸",
    words: [
      "Superman",
      "Wolverine",
      "Iron Man",
      "Thor",
      "Capitán América",
      "Flash",
      "Hulk",
      "Thanos",
      "Magneto",
      "Deadpool",
      "Catwoman",
      "Doctor Extraño",
      "Viuda Negra",
      "Green Lantern",
      "Aquaman",
      "Loki",
      "Lex Luthor",
      "Venom",
      "Star-Lord",
      "Harley Quinn",
    ],
  },
};
