// ─── Rayado Libre Word Bank ──────────────────────────────────────────────────
// Deliberately its own word bank, separate from impostor-data/tutifruti-data —
// this game's words need to be drawable (concrete, mostly nouns), which is a
// different requirement than Impostor's "hard to describe" pick or
// Tutifrutti's "starts with a letter" one, so mixing the pools wouldn't make
// sense even if it were convenient to share.
import { shuffle } from "@juntada/core-utils";

export interface Category {
  label: string;
  icon: string;
  words: string[];
}

// Every word across the given active categories, combined (not one category
// at a time) — shared by the backend engine and LocalGame so "which words
// are even eligible right now" can never drift between the two.
export function activeWordPool(categories: Record<string, Category>, activeKeys: readonly string[]): string[] {
  return activeKeys.flatMap(k => categories[k]?.words ?? []);
}

// Offers 3 words at random from the pool, avoiding ones already used this
// game. `resetUsed` comes back true when the pool didn't have 3 unused words
// left (so this call had to allow repeats) — the caller decides whether/how
// to persist clearing its own used-words bookkeeping, since that lives in a
// different shape server-side (room.usedWords.words) than in LocalGame (a
// plain ref array).
export function pickThreeWords(pool: readonly string[], usedWords: readonly string[]): { words: string[]; resetUsed: boolean } {
  const available = pool.filter(w => !usedWords.includes(w));
  const resetUsed = available.length < 3;
  return { words: shuffle(resetUsed ? pool : available).slice(0, 3), resetUsed };
}

// The label of the category a word comes from, for the word-choice cards
// ("Gato" · Animales). `null` for a word outside every category (the host's
// own custom words). Words don't repeat across categories, so the first
// match is the only one.
export function categoryLabelOf(categories: Record<string, Category>, word: string): string | null {
  for (const category of Object.values(categories)) if (category.words.includes(word)) return category.label;
  return null;
}

export const CATEGORIES: Record<string, Category> = {
  animales: {
    label: "Animales",
    icon: "🦁",
    words: [
      "León",
      "Elefante",
      "Jirafa",
      "Perro",
      "Gato",
      "Pingüino",
      "Serpiente",
      "Tiburón",
      "Pulpo",
      "Araña",
      "Mono",
      "Canguro",
      "Tortuga",
      "Delfín",
      "Búho",
      "Murciélago",
      "Camello",
      "Cebra",
      "Cocodrilo",
      "Águila",
      "Oso",
      "Conejo",
      "Rana",
      "Abeja",
      "Caracol",
      "Pulga",
      "Vaca",
      "Cerdo",
      "Oveja",
      "Gallina",
      "Caballo",
      "Burro",
      "Pato",
      "Ganso",
      "Pavo",
      "Loro",
      "Flamenco",
      "Pavo real",
      "Cisne",
      "Paloma",
      "Colibrí",
      "Pájaro carpintero",
      "Foca",
      "Ballena",
      "Tiburón martillo",
      "Medusa",
      "Estrella de mar",
      "Cangrejo",
      "Langosta",
      "Pez espada",
      "Caballito de mar",
      "Hipopótamo",
      "Rinoceronte",
      "Gorila",
      "Tigre",
      "Leopardo",
      "Lobo",
      "Zorro",
      "Ardilla",
      "Castor",
      "Mapache",
      "Erizo",
      "Koala",
      "Oso panda",
      "Oso polar",
      "Llama",
      "Carpincho",
      "Hormiga",
      "Mariposa",
      "Mosquito",
      "Escarabajo",
      "Vaquita de San Antonio",
      "Libélula",
      "Grillo",
      "Lombriz",
      "Camaleón",
      "Iguana",
      "Dinosaurio",
      "Ratón",
      "Hámster",
      "Jabalí",
      "Ciervo",
      "Alce",
    ],
  },
  objetos: {
    label: "Objetos Cotidianos",
    icon: "🪑",
    words: [
      "Silla",
      "Mesa",
      "Reloj",
      "Paraguas",
      "Bicicleta",
      "Teléfono",
      "Lámpara",
      "Anteojos",
      "Tijeras",
      "Escalera",
      "Llave",
      "Candado",
      "Espejo",
      "Cepillo de dientes",
      "Peine",
      "Sombrero",
      "Zapato",
      "Mochila",
      "Guitarra",
      "Piano",
      "Tambor",
      "Cámara de fotos",
      "Televisor",
      "Ventilador",
      "Escoba",
      "Balde",
      "Martillo",
      "Destornillador",
      "Tijera de podar",
      "Regadera",
      "Tijera",
      "Vela",
      "Cama",
      "Almohada",
      "Tostadora",
      "Heladera",
      "Lavarropas",
      "Control remoto",
      "Computadora",
      "Mouse",
      "Auriculares",
      "Linterna",
      "Serrucho",
      "Plancha",
      "Tenedor",
      "Cuchara",
      "Cuchillo",
      "Olla",
      "Sartén",
      "Taza",
      "Vaso",
      "Botella",
      "Mate",
      "Termo",
      "Valija",
      "Billetera",
      "Globo",
      "Regalo",
      "Carta",
      "Lápiz",
      "Goma de borrar",
      "Regla",
      "Libro",
      "Cuaderno",
      "Sobre",
      "Imán",
      "Enchufe",
      "Bombita de luz",
    ],
  },
  comida: {
    label: "Comida",
    icon: "🍕",
    words: [
      "Pizza",
      "Hamburguesa",
      "Helado",
      "Torta",
      "Sandía",
      "Banana",
      "Pan",
      "Huevo frito",
      "Salchicha",
      "Queso",
      "Taco",
      "Sushi",
      "Espagueti",
      "Pochoclo",
      "Alfajor",
      "Empanada",
      "Choripán",
      "Manzana",
      "Uva",
      "Zanahoria",
      "Papa frita",
      "Donut",
      "Galleta",
      "Chocolate",
      "Café",
      "Limón",
      "Piña",
      "Cereza",
      "Maní",
      "Miel",
      "Pancho",
      "Asado",
      "Milanesa",
      "Fideos",
      "Ravioles",
      "Ñoquis",
      "Sándwich",
      "Tostado",
      "Medialuna",
      "Caramelo",
      "Chupetín",
      "Papas fritas",
      "Pera",
      "Frutilla",
      "Ananá",
      "Naranja",
      "Durazno",
      "Kiwi",
      "Coco",
      "Palta",
      "Tomate",
      "Lechuga",
      "Choclo",
      "Papa",
      "Cebolla",
      "Ajo",
      "Morrón",
      "Berenjena",
      "Zapallo",
      "Brócoli",
      "Hongo",
      "Panqueque",
      "Dona",
      "Churro",
      "Chipá",
      "Flan",
      "Gelatina",
    ],
  },
  profesiones: {
    label: "Profesiones",
    icon: "💼",
    words: [
      "Médico",
      "Bombero",
      "Policía",
      "Cocinero",
      "Maestro",
      "Pintor",
      "Payaso",
      "Astronauta",
      "Pescador",
      "Carpintero",
      "Peluquero",
      "Piloto",
      "Buzo",
      "Mago",
      "Detective",
      "Granjero",
      "Fotógrafo",
      "Panadero",
      "Cartero",
      "Salvavidas",
      "Arquitecto",
      "Jardinero",
      "Electricista",
      "Plomero",
      "Veterinario",
      "Enfermera",
      "Dentista",
      "Maestra",
      "Carnicero",
      "Albañil",
      "Mecánico",
      "Marinero",
      "Bailarina",
      "Cantante",
      "Periodista",
      "Científico",
      "Futbolista",
      "Juez",
      "Barrendero",
      "Colectivero",
      "Taxista",
      "Programador",
      "Chef",
      "Escultor",
      "Guardaparque",
      "Apicultor",
      "Domador",
      "Malabarista",
      "Árbitro",
      "Camarero",
      "Cajero",
      "Heladero",
      "Soldado",
      "Rey",
      "Reina",
    ],
  },
  deportes: {
    label: "Deportes y Juegos",
    icon: "🏅",
    words: [
      "Fútbol",
      "Básquet",
      "Tenis",
      "Natación",
      "Boxeo",
      "Ciclismo",
      "Ajedrez",
      "Surf",
      "Esquí",
      "Yoga",
      "Golf",
      "Voleibol",
      "Karate",
      "Patinaje",
      "Pesca",
      "Escalada",
      "Arquería",
      "Bowling",
      "Rugby",
      "Béisbol",
      "Vóley",
      "Hockey",
      "Skate",
      "Judo",
      "Esgrima",
      "Tiro con arco",
      "Ping pong",
      "Dados",
      "Cartas",
      "Dominó",
      "Rompecabezas",
      "Yoyó",
      "Trompo",
      "Barrilete",
      "Rayuela",
      "Escondida",
      "Mancha",
      "Soga",
      "Pelota",
      "Arco de fútbol",
      "Raqueta",
      "Guantes de boxeo",
      "Casco",
      "Medalla",
      "Trofeo",
      "Silbato",
      "Tabla de surf",
      "Paracaídas",
      "Equitación",
      "Remo",
      "Carrera",
      "Salto en largo",
      "Maratón",
      "Pesas",
      "Hamaca",
      "Tobogán",
      "Subibaja",
      "Calesita",
    ],
  },
  lugares: {
    label: "Lugares",
    icon: "🗺️",
    words: [
      "Playa",
      "Montaña",
      "Desierto",
      "Selva",
      "Isla",
      "Volcán",
      "Castillo",
      "Faro",
      "Cueva",
      "Puente",
      "Aeropuerto",
      "Estadio",
      "Zoológico",
      "Escuela",
      "Hospital",
      "Iglesia",
      "Supermercado",
      "Granja",
      "Cascada",
      "Bosque",
      "Pirámide",
      "Estación de tren",
      "Puerto",
      "Plaza",
      "Parque de diversiones",
      "Circo",
      "Cancha",
      "Museo",
      "Biblioteca",
      "Cine",
      "Teatro",
      "Kiosco",
      "Panadería",
      "Farmacia",
      "Banco",
      "Cárcel",
      "Cementerio",
      "Establo",
      "Iglú",
      "Carpa",
      "Casa del árbol",
      "Rascacielos",
      "Torre Eiffel",
      "Obelisco",
      "Estatua de la Libertad",
      "Gimnasio",
      "Pileta",
      "Baño",
      "Cocina",
      "Garaje",
      "Terraza",
      "Ascensor",
      "Escalera mecánica",
      "Semáforo",
      "Autopista",
      "Ciudad",
      "Pueblo",
    ],
  },
  personajes: {
    label: "Personajes y Fantasía",
    icon: "🦸",
    words: [
      "Superhéroe",
      "Pirata",
      "Fantasma",
      "Vampiro",
      "Dragón",
      "Robot",
      "Extraterrestre",
      "Sirena",
      "Bruja",
      "Duende",
      "Momia",
      "Zombi",
      "Hada",
      "Unicornio",
      "Príncipe",
      "Princesa",
      "Caballero",
      "Gigante",
      "Ninja",
      "Vikingo",
      "Enano",
      "Ogro",
      "Papá Noel",
      "Conejo de Pascua",
      "Esqueleto",
      "Hombre lobo",
      "Frankenstein",
      "Cíclope",
      "Minotauro",
      "Pegaso",
      "Fénix",
      "Genio de la lámpara",
      "Espantapájaros",
      "Muñeco de nieve",
      "Cowboy",
      "Samurái",
      "Cavernícola",
      "Ángel",
      "Diablo",
      "Monstruo",
      "Títere",
      "Marioneta",
      "Muñeca",
      "Oso de peluche",
      "Soldadito de plomo",
      "Pinocho",
      "Caperucita Roja",
      "Lobo feroz",
      "Los tres chanchitos",
      "Cenicienta",
    ],
  },
  naturaleza: {
    label: "Naturaleza y Clima",
    icon: "🌦️",
    words: [
      "Sol",
      "Luna",
      "Estrella",
      "Nube",
      "Lluvia",
      "Nieve",
      "Arcoíris",
      "Rayo",
      "Árbol",
      "Flor",
      "Cactus",
      "Río",
      "Océano",
      "Terremoto",
      "Huracán",
      "Iceberg",
      "Volcán en erupción",
      "Estrella fugaz",
      "Tormenta",
      "Viento",
      "Tornado",
      "Niebla",
      "Granizo",
      "Relámpago",
      "Lago",
      "Laguna",
      "Mar",
      "Ola",
      "Arena",
      "Piedra",
      "Roca",
      "Glaciar",
      "Planeta",
      "Cometa",
      "Eclipse",
      "Atardecer",
      "Amanecer",
      "Hoja",
      "Rama",
      "Tronco",
      "Raíz",
      "Semilla",
      "Pasto",
      "Palmera",
      "Pino",
      "Rosa",
      "Girasol",
      "Margarita",
      "Tulipán",
      "Trébol",
      "Enredadera",
      "Musgo",
      "Charco",
      "Barro",
      "Fuego",
      "Humo",
      "Hielo",
      "Copo de nieve",
      "Gota",
      "Duna",
      "Oasis",
      "Pantano",
      "Isla desierta",
    ],
  },
  transporte: {
    label: "Transporte",
    icon: "🚗",
    words: [
      "Auto",
      "Colectivo",
      "Tren",
      "Subte",
      "Avión",
      "Helicóptero",
      "Barco",
      "Velero",
      "Submarino",
      "Lancha",
      "Canoa",
      "Moto",
      "Monopatín",
      "Patines",
      "Camión",
      "Ambulancia",
      "Camión de bomberos",
      "Patrullero",
      "Taxi",
      "Tractor",
      "Grúa",
      "Excavadora",
      "Cohete",
      "Nave espacial",
      "Globo aerostático",
      "Dirigible",
      "Carro",
      "Carruaje",
      "Trineo",
      "Tranvía",
      "Teleférico",
      "Jet ski",
      "Kayak",
      "Balsa",
      "Casa rodante",
      "Limusina",
      "Auto de carrera",
      "Karting",
      "Tanque",
      "Aerosilla",
      "Carretilla",
      "Cochecito de bebé",
      "Silla de ruedas",
      "Motoneta",
      "Cuatriciclo",
      "Camioneta",
    ],
  },
  ropa: {
    label: "Ropa y Accesorios",
    icon: "👕",
    words: [
      "Remera",
      "Pantalón",
      "Short",
      "Pollera",
      "Vestido",
      "Campera",
      "Buzo de lana",
      "Saco",
      "Corbata",
      "Camisa",
      "Medias",
      "Zapatillas",
      "Zapatos",
      "Botas",
      "Ojotas",
      "Sandalias",
      "Gorra",
      "Gorro de lana",
      "Bufanda",
      "Guantes",
      "Cinturón",
      "Tiradores",
      "Pijama",
      "Malla",
      "Bikini",
      "Delantal",
      "Piloto de lluvia",
      "Pañuelo",
      "Reloj pulsera",
      "Collar",
      "Anillo",
      "Aros",
      "Pulsera",
      "Corona",
      "Tiara",
      "Vincha",
      "Hebilla",
      "Cartera",
      "Riñonera",
      "Barbijo",
      "Capa",
      "Disfraz",
      "Uniforme",
      "Traje",
      "Chaleco",
      "Poncho",
      "Boina",
    ],
  },
  musica: {
    label: "Música e Instrumentos",
    icon: "🎸",
    words: [
      "Batería",
      "Violín",
      "Trompeta",
      "Flauta",
      "Saxofón",
      "Arpa",
      "Acordeón",
      "Bandoneón",
      "Maracas",
      "Pandereta",
      "Xilófono",
      "Triángulo",
      "Platillos",
      "Bajo",
      "Ukelele",
      "Charango",
      "Armónica",
      "Gaita",
      "Trombón",
      "Tuba",
      "Violonchelo",
      "Micrófono",
      "Parlante",
      "Radio",
      "Tocadiscos",
      "Disco",
      "Casete",
      "Partitura",
      "Nota musical",
      "Director de orquesta",
      "Orquesta",
      "Banda de rock",
      "Recital",
      "Karaoke",
      "Caja musical",
      "Campana",
      "Metrónomo",
      "Atril",
      "Piano de cola",
      "Guitarra eléctrica",
      "Teclado",
      "Bombo",
      "Quena",
      "Castañuelas",
      "Cascabel",
    ],
  },
  cuerpo: {
    label: "Cuerpo Humano",
    icon: "🫀",
    words: [
      "Ojo",
      "Nariz",
      "Boca",
      "Oreja",
      "Diente",
      "Lengua",
      "Labios",
      "Cejas",
      "Pestañas",
      "Pelo",
      "Barba",
      "Bigote",
      "Mano",
      "Dedo",
      "Uña",
      "Pie",
      "Rodilla",
      "Codo",
      "Hombro",
      "Brazo",
      "Pierna",
      "Panza",
      "Ombligo",
      "Espalda",
      "Cuello",
      "Cabeza",
      "Cara",
      "Corazón",
      "Cerebro",
      "Pulmones",
      "Hueso",
      "Calavera",
      "Músculo",
      "Huella digital",
      "Pisada",
      "Estornudo",
      "Bostezo",
      "Sonrisa",
      "Guiño",
      "Lágrima",
      "Moretón",
      "Curita",
      "Muleta",
      "Yeso",
      "Termómetro",
      "Jeringa",
      "Pastilla",
      "Estetoscopio",
      "Radiografía",
      "Cepillo de pelo",
    ],
  },
};
