// ─── Design tokens / inline-style dictionary ─────────────────────────────────
import type { CSSProperties } from "react";

export const S = {
  app: {
    minHeight: "100vh",
    background: "#0f0c1d",
    fontFamily: "'Syne', sans-serif",
    color: "#e8e4f0",
    overflowX: "hidden",
  } satisfies CSSProperties,
  wrap: { maxWidth: 480, margin: "0 auto", padding: "0 16px 60px" } satisfies CSSProperties,
  header: {
    textAlign: "center",
    padding: "32px 0 20px",
    borderBottom: "1px solid rgba(127,119,221,0.2)",
    marginBottom: 24,
  } satisfies CSSProperties,
  title: {
    fontSize: 38,
    fontWeight: 800,
    letterSpacing: "-0.03em",
    background: "linear-gradient(90deg,#AFA9EC,#5DCAA5)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    margin: 0,
  } satisfies CSSProperties,
  card: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(127,119,221,0.18)",
    borderRadius: 16,
    padding: "18px 20px",
    marginBottom: 14,
  } satisfies CSSProperties,
  cardHighlight: {
    background: "rgba(127,119,221,0.1)",
    border: "1px solid rgba(127,119,221,0.35)",
    borderRadius: 16,
    padding: "18px 20px",
    marginBottom: 14,
  } satisfies CSSProperties,
  label: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color: "#7F77DD",
    marginBottom: 10,
    display: "block",
  } satisfies CSSProperties,
  input: {
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(127,119,221,0.25)",
    borderRadius: 10,
    padding: "11px 14px",
    color: "#e8e4f0",
    fontSize: 15,
    fontFamily: "inherit",
    width: "100%",
    outline: "none",
    boxSizing: "border-box",
  } satisfies CSSProperties,
  btn: (variant: "primary" | "success" | "danger" | "ghost" = "primary", disabled = false): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "13px 28px",
    borderRadius: 12,
    fontWeight: 700,
    fontSize: 15,
    cursor: disabled ? "default" : "pointer",
    border: "none",
    transition: "all 0.15s",
    fontFamily: "inherit",
    width: "100%",
    boxSizing: "border-box",
    opacity: disabled ? 0.4 : 1,
    ...(variant === "primary"
      ? {
          background: "linear-gradient(135deg,#7F77DD,#534AB7)",
          color: "#fff",
          boxShadow: disabled ? "none" : "0 4px 20px rgba(127,119,221,0.35)",
        }
      : variant === "success"
        ? {
            background: "linear-gradient(135deg,#1D9E75,#0F6E56)",
            color: "#fff",
            boxShadow: disabled ? "none" : "0 4px 20px rgba(29,158,117,0.3)",
          }
        : variant === "danger"
          ? { background: "rgba(226,75,74,0.15)", color: "#F09595", border: "1px solid rgba(226,75,74,0.3)" }
          : { background: "rgba(127,119,221,0.1)", color: "#AFA9EC", border: "1px solid rgba(127,119,221,0.25)" }),
  }),
  bigReveal: {
    fontSize: 28,
    fontWeight: 800,
    color: "#AFA9EC",
    textAlign: "center",
    letterSpacing: "-0.02em",
    margin: "12px 0",
    lineHeight: 1.2,
  } satisfies CSSProperties,
  muted: { color: "#6b6490", fontSize: 13 } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#7F77DD",
    margin: "0 2px 8px",
  } satisfies CSSProperties,
  searchBar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(127,119,221,0.25)",
    borderRadius: 10,
    padding: "0 12px",
    height: 40,
    marginBottom: 18,
  } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    background: "none",
    border: "none",
    outline: "none",
    color: "#e8e4f0",
    fontSize: 14,
    fontFamily: "inherit",
  } satisfies CSSProperties,
  catalogCard: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(127,119,221,0.18)",
    borderRadius: 14,
    overflow: "hidden",
    cursor: "pointer",
  } satisfies CSSProperties,
  catalogThumb: {
    aspectRatio: "4 / 3",
    background:
      "repeating-linear-gradient(135deg, rgba(127,119,221,0.16) 0px, rgba(127,119,221,0.16) 8px, rgba(127,119,221,0.06) 8px, rgba(127,119,221,0.06) 16px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 32,
    position: "relative",
  } satisfies CSSProperties,
  catalogName: {
    padding: "10px 12px",
    fontWeight: 700,
    fontSize: 14,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  soonBadge: {
    position: "absolute",
    top: 6,
    right: 6,
    background: "rgba(0,0,0,0.5)",
    color: "#AFA9EC",
    fontSize: 9,
    fontWeight: 700,
    padding: "2px 7px",
    borderRadius: 20,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  } satisfies CSSProperties,
  pill: (on: boolean): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 12px",
    borderRadius: 20,
    fontSize: 12,
    fontWeight: 600,
    background: on ? "rgba(29,158,117,0.15)" : "rgba(255,255,255,0.06)",
    color: on ? "#5DCAA5" : "#6b6490",
    border: `1px solid ${on ? "rgba(29,158,117,0.35)" : "rgba(255,255,255,0.08)"}`,
  }),
  toggle: (on: boolean): CSSProperties => ({
    width: 44,
    height: 24,
    borderRadius: 12,
    position: "relative",
    flexShrink: 0,
    background: on ? "rgba(29,158,117,0.8)" : "rgba(255,255,255,0.1)",
    border: `1px solid ${on ? "rgba(29,158,117,0.5)" : "rgba(255,255,255,0.1)"}`,
    cursor: "pointer",
    transition: "background 0.2s",
  }),
  knob: (on: boolean): CSSProperties => ({
    position: "absolute",
    top: 2,
    left: on ? 22 : 2,
    width: 18,
    height: 18,
    borderRadius: "50%",
    background: "#fff",
    transition: "left 0.2s",
    boxShadow: "0 1px 4px rgba(0,0,0,0.3)",
  }),
  namePill: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "5px 12px 5px 6px",
    borderRadius: 999,
    background: "rgba(127,119,221,0.1)",
    border: "1px solid rgba(127,119,221,0.3)",
    cursor: "pointer",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  roundIconButton: {
    width: 40,
    height: 40,
    borderRadius: 999,
    border: "none",
    cursor: "pointer",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    background: "linear-gradient(135deg,#7F77DD,#534AB7)",
    color: "#fff",
    fontFamily: "inherit",
    boxShadow: "0 4px 14px rgba(127,119,221,0.35)",
    transition: "transform 0.15s",
  } satisfies CSSProperties,
  dropdownMenu: {
    position: "absolute",
    top: "calc(100% + 8px)",
    right: 0,
    width: 190,
    background: "#161029",
    border: "1px solid rgba(127,119,221,0.35)",
    borderRadius: 12,
    boxShadow: "0 12px 32px rgba(0,0,0,0.5)",
    padding: 6,
    zIndex: 5,
    textAlign: "left",
  } satisfies CSSProperties,
  segmentedControl: {
    display: "flex",
    background: "rgba(255,255,255,0.05)",
    borderRadius: 10,
    padding: 3,
    marginBottom: 10,
    gap: 3,
  } satisfies CSSProperties,
  segmentedOption: {
    flex: 1,
    textAlign: "center",
    padding: "8px 0",
    borderRadius: 8,
    background: "none",
    border: "none",
    color: "#8079a8",
    fontSize: 12,
    fontWeight: 700,
    fontFamily: "inherit",
    cursor: "pointer",
  } satisfies CSSProperties,
  segmentedOptionActive: {
    flex: 1,
    textAlign: "center",
    padding: "8px 0",
    borderRadius: 8,
    background: "linear-gradient(135deg,#7F77DD,#534AB7)",
    border: "none",
    color: "#fff",
    fontSize: 12,
    fontWeight: 700,
    fontFamily: "inherit",
    cursor: "pointer",
  } satisfies CSSProperties,
  modeRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(127,119,221,0.18)",
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    cursor: "pointer",
  } satisfies CSSProperties,
  modeIconBadge: {
    width: 38,
    height: 38,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 19,
    flexShrink: 0,
  } satisfies CSSProperties,
  modeRowTitle: {
    fontWeight: 800,
    fontSize: 15,
    margin: "0 0 2px",
    fontFamily: "'Syne', sans-serif",
  } satisfies CSSProperties,
  modeRowSubtitle: {
    color: "#6b6490",
    fontSize: 12,
    margin: 0,
  } satisfies CSSProperties,
  dropdownMenuItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "10px 10px",
    background: "none",
    border: "none",
    borderRadius: 8,
    color: "#e8e4f0",
    fontSize: 13,
    fontWeight: 700,
    fontFamily: "inherit",
    cursor: "pointer",
    boxSizing: "border-box",
  } satisfies CSSProperties,
};
